// src/components/chat/Settings/Tools.tsx
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Plus } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { useAppStore } from '@/store';

interface ToolServer {
  url: string;
  key?: string;
}

interface ToolsProps {
  saveSettings: (settings: Record<string, unknown>) => Promise<void>;
}

export default function Tools({ saveSettings }: ToolsProps) {
  const { t } = useTranslation();
  const { settings } = useAppStore();

  const [servers, setServers] = useState<ToolServer[] | null>(null);
  const [showConnectionModal, setShowConnectionModal] = useState(false);

  useEffect(() => {
    setServers(settings?.toolServers ?? []);
  }, []);

  const addConnectionHandler = async (server: ToolServer) => {
    const newServers = [...(servers || []), server];
    setServers(newServers);
    await updateHandler(newServers);
    setShowConnectionModal(false);
  };

  const deleteConnectionHandler = async (index: number) => {
    const newServers = servers?.filter((_, i) => i !== index) || [];
    setServers(newServers);
    await updateHandler(newServers);
  };

  const updateHandler = async (updatedServers: ToolServer[]) => {
    await saveSettings({
      toolServers: updatedServers,
    });

    toast.success(t('Settings saved successfully!'));
  };

  if (servers === null) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground">{t('Loading...')}</div>
      </div>
    );
  }

  return (
    <TooltipProvider>
      <div className="flex flex-col h-full text-sm">
        <div className="overflow-y-auto h-full">
          <div className="pr-1.5">
            <div className="flex justify-between items-center mb-2">
              <div className="font-medium">{t('Manage Tool Servers')}</div>

              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => {
                      setShowConnectionModal(true);
                    }}
                  >
                    <Plus className="h-4 w-4" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>{t('Add Connection')}</p>
                </TooltipContent>
              </Tooltip>
            </div>

            <div className="space-y-2">
              {servers.length > 0 ? (
                servers.map((server, idx) => (
                  <div
                    key={idx}
                    className="flex items-center justify-between p-3 border rounded-lg hover:bg-accent/50 transition"
                  >
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-medium truncate">{server.url}</div>
                    </div>
                    <div className="flex gap-2 ml-4">
                      <Button
                        variant="destructive"
                        size="sm"
                        onClick={() => deleteConnectionHandler(idx)}
                      >
                        {t('Delete')}
                      </Button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-8 text-muted-foreground">
                  {t('No tool servers configured')}
                </div>
              )}
            </div>

            <div className="mt-4 text-xs text-gray-500">
              {t('Connect to your own OpenAPI compatible external tool servers.')}
              <br />
              {t(
                'CORS must be properly configured by the provider to allow requests from Open WebUI.'
              )}
            </div>
          </div>
        </div>
      </div>
    </TooltipProvider>
  );
}

// svelte-frontend/src/lib/components/chat/Settings/Tools.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { createEventDispatcher, onMount, getContext } from 'svelte';
	import { getModels as _getModels, getToolServersData } from '$lib/apis';

	const dispatch = createEventDispatcher();
	const i18n = getContext('i18n');

	import { settings, toolServers } from '$lib/stores';

	import Spinner from '$lib/components/common/Spinner.svelte';
	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import Plus from '$lib/components/icons/Plus.svelte';
	import Connection from './Tools/Connection.svelte';

	import AddToolServerModal from '$lib/components/AddToolServerModal.svelte';

	export let saveSettings: Function;

	let servers = null;
	let showConnectionModal = false;

	const addConnectionHandler = async (server) => {
		servers = [...servers, server];
		await updateHandler();
	};

	const updateHandler = async () => {
		await saveSettings({
			toolServers: servers
		});

		let toolServersData = await getToolServersData($settings?.toolServers ?? []);
		toolServersData = toolServersData.filter((data) => {
			if (data.error) {
				toast.error(
					$i18n.t(`Failed to connect to {{URL}} OpenAPI tool server`, {
						URL: data?.url
					})
				);
				return false;
			}

			return true;
		});
		toolServers.set(toolServersData);
	};

	onMount(async () => {
		servers = $settings?.toolServers ?? [];
	});
</script>

<AddToolServerModal bind:show={showConnectionModal} onSubmit={addConnectionHandler} direct />

<form
	id="tab-tools"
	class="flex flex-col h-full justify-between text-sm"
	on:submit|preventDefault={() => {
		updateHandler();
	}}
>
	<div class=" overflow-y-scroll scrollbar-hidden h-full">
		{#if servers !== null}
			<div class="">
				<div class="pr-1.5">
					<!-- {$i18n.t(`Failed to connect to {{URL}} OpenAPI tool server`, {
						URL: 'server?.url'
					})} -->
					<div class="">
						<div class="flex justify-between items-center mb-0.5">
							<div class="font-medium">{$i18n.t('Manage Tool Servers')}</div>

							<Tooltip content={$i18n.t(`Add Connection`)}>
								<button
									aria-label={$i18n.t(`Add Connection`)}
									class="px-1"
									on:click={() => {
										showConnectionModal = true;
									}}
									type="button"
								>
									<Plus />
								</button>
							</Tooltip>
						</div>

						<div class="flex flex-col gap-1.5">
							{#each servers as server, idx}
								<Connection
									bind:connection={server}
									direct
									onSubmit={() => {
										updateHandler();
									}}
									onDelete={() => {
										servers = servers.filter((_, i) => i !== idx);
										updateHandler();
									}}
								/>
							{/each}
						</div>
					</div>

					<div class="my-1.5">
						<div
							class={`text-xs 
								${($settings?.highContrastMode ?? false) ? 'text-gray-800 dark:text-gray-100' : 'text-gray-500'}`}
						>
							{$i18n.t('Connect to your own OpenAPI compatible external tool servers.')}
							<br />
							{$i18n.t(
								'CORS must be properly configured by the provider to allow requests from Open WebUI.'
							)}
						</div>
					</div>
				</div>
			</div>
		{:else}
			<div class="flex h-full justify-center">
				<div class="my-auto">
					<Spinner className="size-6" />
				</div>
			</div>
		{/if}
	</div>

	<div class="flex justify-end pt-3 text-sm font-medium">
		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			type="submit"
		>
			{$i18n.t('Save')}
		</button>
	</div>
</form>
