// src/components/admin/Settings/Connections.tsx
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Separator } from '@/components/ui/separator';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { Plus, Settings as SettingsIcon, Trash2, Layers } from 'lucide-react';
import { getOpenAIConfig, updateOpenAIConfig, getOpenAIModels } from '@/lib/apis/openai';
import { getConnectionsConfig, setConnectionsConfig } from '@/lib/apis/configs';
import { getBackendConfig, getModels as getModelsAPI } from '@/lib/apis';
import AddConnectionModal from '@/components/admin/AddConnectionModal';
import { useAppStore } from '@/store';

interface OpenAIConfig {
  ENABLE_OPENAI_API: boolean;
  OPENAI_API_BASE_URLS: string[];
  OPENAI_API_KEYS: string[];
  OPENAI_API_CONFIGS: Record<string, any>;
}

interface ConnectionsConfigType {
  ENABLE_DIRECT_CONNECTIONS: boolean;
  ENABLE_BASE_MODELS_CACHE: boolean;
}

interface Connection {
  url: string;
  key: string;
  config: Record<string, unknown>;
  pipeline?: boolean;
}

export default function Connections() {
  const { t } = useTranslation();
  const { settings, setConfig, setModels } = useAppStore();
  const [enableOpenAIAPI, setEnableOpenAIAPI] = useState<boolean | null>(null);
  const [openaiApiBaseUrls, setOpenaiApiBaseUrls] = useState<string[]>(['']);
  const [openaiApiKeys, setOpenaiApiKeys] = useState<string[]>(['']);
  const [openaiApiConfigs, setOpenaiApiConfigs] = useState<Record<string, any>>({});
  const [connectionsConfig, setConnectionsConfigState] = useState<ConnectionsConfigType | null>(null);
  const [pipelineUrls, setPipelineUrls] = useState<Record<string, boolean>>({});
  
  const [showAddModal, setShowAddModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [editingConnection, setEditingConnection] = useState<Connection | null>(null);

  useEffect(() => {
    const init = async () => {
      const token = localStorage.getItem('token') || '';

      try {
        const [openaiConfig, connConfig] = await Promise.all([
          getOpenAIConfig(token),
          getConnectionsConfig(token)
        ]);

        if (openaiConfig) {
          setEnableOpenAIAPI(openaiConfig.ENABLE_OPENAI_API);
          setOpenaiApiBaseUrls(openaiConfig.OPENAI_API_BASE_URLS);
          setOpenaiApiKeys(openaiConfig.OPENAI_API_KEYS);
          setOpenaiApiConfigs(openaiConfig.OPENAI_API_CONFIGS);

          if (openaiConfig.ENABLE_OPENAI_API) {
            // Check for pipelines
            const pipelines: Record<string, boolean> = {};
            for (const [idx, url] of openaiConfig.OPENAI_API_BASE_URLS.entries()) {
              if (!openaiConfig.OPENAI_API_CONFIGS[idx]) {
                openaiConfig.OPENAI_API_CONFIGS[idx] = openaiConfig.OPENAI_API_CONFIGS[url] || {};
              }

              const config = openaiConfig.OPENAI_API_CONFIGS[idx] || {};
              if (config?.enable ?? true) {
                try {
                  const res = await getOpenAIModels(token, idx);
                  if (res.pipelines) {
                    pipelines[url] = true;
                  }
                } catch (error) {
                  console.error(`Failed to check pipeline for ${url}:`, error);
                }
              }
            }
            setPipelineUrls(pipelines);
          }
        }

        if (connConfig) {
          setConnectionsConfigState(connConfig);
        }
      } catch (error) {
        console.error('Failed to load connections settings:', error);
        toast.error(t('Failed to load settings'));
      }
    };

    init();
  }, [t]);

  const updateOpenAIHandler = async () => {
    if (enableOpenAIAPI === null) return;

    const token = localStorage.getItem('token') || '';

    try {
      // Remove trailing slashes
      const cleanedUrls = openaiApiBaseUrls.map(url => url.replace(/\/$/, ''));

      // Sync keys with URLs
      let syncedKeys = [...openaiApiKeys];
      if (syncedKeys.length < cleanedUrls.length) {
        const diff = cleanedUrls.length - syncedKeys.length;
        syncedKeys = [...syncedKeys, ...Array(diff).fill('')];
      } else if (syncedKeys.length > cleanedUrls.length) {
        syncedKeys = syncedKeys.slice(0, cleanedUrls.length);
      }

      await updateOpenAIConfig(token, {
        ENABLE_OPENAI_API: enableOpenAIAPI,
        OPENAI_API_BASE_URLS: cleanedUrls,
        OPENAI_API_KEYS: syncedKeys,
        OPENAI_API_CONFIGS: openaiApiConfigs
      });

      toast.success(t('OpenAI API settings updated'));
      
      // Reload models and config
      const [newModels, newConfig] = await Promise.all([
        getModelsAPI(token, settings?.directConnections ?? null, false, true),
        getBackendConfig()
      ]);
      
      if (newModels) {
        setModels(newModels);
      }
      if (newConfig) {
        setConfig(newConfig);
      }
    } catch (error) {
      console.error('Failed to update OpenAI settings:', error);
      toast.error(String(error));
    }
  };

  const updateConnectionsHandler = async () => {
    if (!connectionsConfig) return;

    const token = localStorage.getItem('token') || '';

    try {
      await setConnectionsConfig(token, connectionsConfig);
      toast.success(t('Connections settings updated'));
      
      // Reload models and config
      const [newModels, newConfig] = await Promise.all([
        getModelsAPI(token, settings?.directConnections ?? null, false, true),
        getBackendConfig()
      ]);
      
      if (newModels) {
        setModels(newModels);
      }
      if (newConfig) {
        setConfig(newConfig);
      }
    } catch (error) {
      console.error('Failed to update connections settings:', error);
      toast.error(String(error));
    }
  };

  const addConnection = async (connection: Connection) => {
    const newUrls = [...openaiApiBaseUrls, connection.url];
    const newKeys = [...openaiApiKeys, connection.key];
    const newConfigs = { ...openaiApiConfigs };
    newConfigs[openaiApiBaseUrls.length] = connection.config;

    setOpenaiApiBaseUrls(newUrls);
    setOpenaiApiKeys(newKeys);
    setOpenaiApiConfigs(newConfigs);

    // Update backend
    const token = localStorage.getItem('token') || '';
    try {
      await updateOpenAIConfig(token, {
        ENABLE_OPENAI_API: enableOpenAIAPI!,
        OPENAI_API_BASE_URLS: newUrls,
        OPENAI_API_KEYS: newKeys,
        OPENAI_API_CONFIGS: newConfigs
      });
      toast.success(t('Connection added successfully'));
      
      // Reload models
      const newModels = await getModelsAPI(token, settings?.directConnections ?? null, false, true);
      if (newModels) {
        setModels(newModels);
      }
    } catch (error) {
      toast.error(String(error));
    }
  };

  const updateConnection = async (connection: Connection) => {
    if (editingIndex === null) return;

    const newUrls = [...openaiApiBaseUrls];
    const newKeys = [...openaiApiKeys];
    const newConfigs = { ...openaiApiConfigs };

    newUrls[editingIndex] = connection.url;
    newKeys[editingIndex] = connection.key;
    newConfigs[editingIndex] = connection.config;

    setOpenaiApiBaseUrls(newUrls);
    setOpenaiApiKeys(newKeys);
    setOpenaiApiConfigs(newConfigs);

    // Update backend
    const token = localStorage.getItem('token') || '';
    try {
      await updateOpenAIConfig(token, {
        ENABLE_OPENAI_API: enableOpenAIAPI!,
        OPENAI_API_BASE_URLS: newUrls,
        OPENAI_API_KEYS: newKeys,
        OPENAI_API_CONFIGS: newConfigs
      });
      toast.success(t('Connection updated successfully'));
      
      // Reload models
      const newModels = await getModelsAPI(token, settings?.directConnections ?? null, false, true);
      if (newModels) {
        setModels(newModels);
      }
    } catch (error) {
      toast.error(String(error));
    }
  };

  const deleteConnection = async (index: number) => {
    const newUrls = openaiApiBaseUrls.filter((_, idx) => idx !== index);
    const newKeys = openaiApiKeys.filter((_, idx) => idx !== index);
    
    const newConfigs: Record<string, any> = {};
    newUrls.forEach((url, newIdx) => {
      newConfigs[newIdx] = openaiApiConfigs[newIdx < index ? newIdx : newIdx + 1];
    });

    setOpenaiApiBaseUrls(newUrls);
    setOpenaiApiKeys(newKeys);
    setOpenaiApiConfigs(newConfigs);

    // Update backend
    const token = localStorage.getItem('token') || '';
    try {
      await updateOpenAIConfig(token, {
        ENABLE_OPENAI_API: enableOpenAIAPI!,
        OPENAI_API_BASE_URLS: newUrls,
        OPENAI_API_KEYS: newKeys,
        OPENAI_API_CONFIGS: newConfigs
      });
      toast.success(t('Connection deleted successfully'));
      
      // Reload models
      const newModels = await getModelsAPI(token, settings?.directConnections ?? null, false, true);
      if (newModels) {
        setModels(newModels);
      }
    } catch (error) {
      toast.error(String(error));
    }
  };

  const openEditModal = (index: number) => {
    const connection: Connection = {
      url: openaiApiBaseUrls[index],
      key: openaiApiKeys[index],
      config: openaiApiConfigs[index] || {}
    };
    setEditingIndex(index);
    setEditingConnection(connection);
    setShowEditModal(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    await updateOpenAIHandler();
  };

  if (enableOpenAIAPI === null || !connectionsConfig) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground">{t('Loading...')}</div>
      </div>
    );
  }

  return (
    <>
      <AddConnectionModal
        open={showAddModal}
        onOpenChange={setShowAddModal}
        onSubmit={addConnection}
        edit={false}
      />

      <AddConnectionModal
        open={showEditModal}
        onOpenChange={(open) => {
          setShowEditModal(open);
          if (!open) {
            setEditingIndex(null);
            setEditingConnection(null);
          }
        }}
        onSubmit={updateConnection}
        onDelete={() => {
          if (editingIndex !== null) {
            deleteConnection(editingIndex);
          }
        }}
        connection={editingConnection}
        edit={true}
      />

      <form onSubmit={handleSubmit} className="flex flex-col h-full justify-between text-sm">
        <div className="overflow-y-scroll scrollbar-hidden h-full">
          <div className="mb-3.5">
            <div className="mb-2.5 text-base font-medium">{t('General')}</div>
            <Separator />

            <div className="my-2">
              <div className="mt-2 space-y-2">
                <div className="flex justify-between items-center text-sm">
                  <Label className="font-medium">{t('OpenAI API')}</Label>
                  <Switch
                    checked={enableOpenAIAPI}
                    onCheckedChange={async (checked) => {
                      setEnableOpenAIAPI(checked);
                      const token = localStorage.getItem('token') || '';
                      try {
                        await updateOpenAIConfig(token, {
                          ENABLE_OPENAI_API: checked,
                          OPENAI_API_BASE_URLS: openaiApiBaseUrls,
                          OPENAI_API_KEYS: openaiApiKeys,
                          OPENAI_API_CONFIGS: openaiApiConfigs
                        });
                        toast.success(t('OpenAI API settings updated'));
                        
                        // Reload models
                        const newModels = await getModelsAPI(token, settings?.directConnections ?? null, false, true);
                        if (newModels) {
                          setModels(newModels);
                        }
                      } catch (error) {
                        toast.error(String(error));
                      }
                    }}
                  />
                </div>

                {enableOpenAIAPI && (
                  <div>
                    <div className="flex justify-between items-center mb-1.5">
                      <Label className="font-medium text-xs">{t('Manage OpenAI API Connections')}</Label>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Button
                            type="button"
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8"
                            onClick={() => setShowAddModal(true)}
                          >
                            <Plus className="h-4 w-4" />
                          </Button>
                        </TooltipTrigger>
                        <TooltipContent>{t('Add Connection')}</TooltipContent>
                      </Tooltip>
                    </div>

                    <div className="flex flex-col gap-1.5 mt-1.5">
                      {openaiApiBaseUrls.map((url, idx) => {
                        const config = openaiApiConfigs[idx] || {};
                        const isEnabled = config?.enable ?? true;
                        const isPipeline = pipelineUrls[url];

                        return (
                          <div key={idx} className="flex w-full gap-2 items-center">
                            <Tooltip>
                              <TooltipTrigger asChild className="w-full">
                                <div className={`flex w-full gap-2 relative ${!isEnabled ? 'opacity-50' : ''}`}>
                                  <div className="flex-1 relative">
                                    <Input
                                      className="w-full pr-8"
                                      placeholder={t('API Base URL')}
                                      value={url}
                                      readOnly
                                    />
                                    {isPipeline && (
                                      <div className="absolute top-2.5 right-2">
                                        <Tooltip>
                                          <TooltipTrigger asChild>
                                            <div className="h-5 w-5 flex items-center justify-center">
                                              <Layers className="h-4 w-4" />
                                            </div>
                                          </TooltipTrigger>
                                          <TooltipContent>Pipelines</TooltipContent>
                                        </Tooltip>
                                      </div>
                                    )}
                                  </div>
                                </div>
                              </TooltipTrigger>
                              <TooltipContent>
                                {t('WebUI will make requests to "{{url}}/chat/completions"', { url })}
                              </TooltipContent>
                            </Tooltip>

                            <div className="flex gap-1">
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <Button
                                    type="button"
                                    variant="ghost"
                                    size="icon"
                                    className="h-8 w-8"
                                    onClick={() => openEditModal(idx)}
                                  >
                                    <SettingsIcon className="h-4 w-4" />
                                  </Button>
                                </TooltipTrigger>
                                <TooltipContent>{t('Configure')}</TooltipContent>
                              </Tooltip>

                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <Button
                                    type="button"
                                    variant="ghost"
                                    size="icon"
                                    className="h-8 w-8 hover:text-destructive"
                                    onClick={() => deleteConnection(idx)}
                                  >
                                    <Trash2 className="h-4 w-4" />
                                  </Button>
                                </TooltipTrigger>
                                <TooltipContent>{t('Delete')}</TooltipContent>
                              </Tooltip>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}
              </div>
            </div>

            <div className="my-2">
              <div className="flex justify-between items-center text-sm">
                <Label className="font-medium">{t('Direct Connections')}</Label>
                <Switch
                  checked={connectionsConfig.ENABLE_DIRECT_CONNECTIONS}
                  onCheckedChange={async (checked) => {
                    setConnectionsConfigState({
                      ...connectionsConfig,
                      ENABLE_DIRECT_CONNECTIONS: checked
                    });
                    try {
                      const token = localStorage.getItem('token') || '';
                      await setConnectionsConfig(token, {
                        ...connectionsConfig,
                        ENABLE_DIRECT_CONNECTIONS: checked
                      });
                      toast.success(t('Connections settings updated'));
                    } catch (error) {
                      toast.error(String(error));
                    }
                  }}
                />
              </div>
              <div className="mt-1 text-xs text-muted-foreground">
                {t('Direct Connections allow users to connect to their own OpenAI compatible API endpoints.')}
              </div>
            </div>

            <Separator className="my-2" />

            <div className="my-2">
              <div className="flex justify-between items-center text-sm">
                <Label className="text-xs font-medium">{t('Cache Base Model List')}</Label>
                <Switch
                  checked={connectionsConfig.ENABLE_BASE_MODELS_CACHE}
                  onCheckedChange={async (checked) => {
                    setConnectionsConfigState({
                      ...connectionsConfig,
                      ENABLE_BASE_MODELS_CACHE: checked
                    });
                    try {
                      const token = localStorage.getItem('token') || '';
                      await setConnectionsConfig(token, {
                        ...connectionsConfig,
                        ENABLE_BASE_MODELS_CACHE: checked
                      });
                      toast.success(t('Connections settings updated'));
                    } catch (error) {
                      toast.error(String(error));
                    }
                  }}
                />
              </div>
              <div className="mt-1 text-xs text-muted-foreground">
                {t('Base Model List Cache speeds up access by fetching base models only at startup or on settings save—faster, but may not show recent base model changes.')}
              </div>
            </div>
          </div>
        </div>

        <div className="flex justify-end pt-3 text-sm font-medium">
          <Button type="submit" className="px-3.5 py-1.5 rounded-full">
            {t('Save')}
          </Button>
        </div>
      </form>
    </>
  );
}

// src/lib/components/admin/Settings/Connections.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { createEventDispatcher, onMount, getContext, tick } from 'svelte';

	const dispatch = createEventDispatcher();

	import { getOpenAIConfig, updateOpenAIConfig, getOpenAIModels } from '$lib/apis/openai';
	import { getModels as _getModels, getBackendConfig } from '$lib/apis';
	import { getConnectionsConfig, setConnectionsConfig } from '$lib/apis/configs';

	import { config, models, settings, user } from '$lib/stores';

	import Switch from '$lib/components/common/Switch.svelte';
	import Spinner from '$lib/components/common/Spinner.svelte';
	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import Plus from '$lib/components/icons/Plus.svelte';

	import OpenAIConnection from './Connections/OpenAIConnection.svelte';
	import AddConnectionModal from '$lib/components/AddConnectionModal.svelte';

	const i18n = getContext('i18n');

	const getModels = async () => {
		const models = await _getModels(
			localStorage.token,
			$config?.features?.enable_direct_connections && ($settings?.directConnections ?? null),
			false,
			true
		);
		return models;
	};

	// External
	let OPENAI_API_KEYS = [''];
	let OPENAI_API_BASE_URLS = [''];
	let OPENAI_API_CONFIGS = {};

	let ENABLE_OPENAI_API: null | boolean = null;

	let connectionsConfig = null;

	let pipelineUrls = {};
	let showAddOpenAIConnectionModal = false;

	const updateOpenAIHandler = async () => {
		if (ENABLE_OPENAI_API !== null) {
			// Remove trailing slashes
			OPENAI_API_BASE_URLS = OPENAI_API_BASE_URLS.map((url) => url.replace(/\/$/, ''));

			// Check if API KEYS length is same than API URLS length
			if (OPENAI_API_KEYS.length !== OPENAI_API_BASE_URLS.length) {
				// if there are more keys than urls, remove the extra keys
				if (OPENAI_API_KEYS.length > OPENAI_API_BASE_URLS.length) {
					OPENAI_API_KEYS = OPENAI_API_KEYS.slice(0, OPENAI_API_BASE_URLS.length);
				}

				// if there are more urls than keys, add empty keys
				if (OPENAI_API_KEYS.length < OPENAI_API_BASE_URLS.length) {
					const diff = OPENAI_API_BASE_URLS.length - OPENAI_API_KEYS.length;
					for (let i = 0; i < diff; i++) {
						OPENAI_API_KEYS.push('');
					}
				}
			}

			const res = await updateOpenAIConfig(localStorage.token, {
				ENABLE_OPENAI_API: ENABLE_OPENAI_API,
				OPENAI_API_BASE_URLS: OPENAI_API_BASE_URLS,
				OPENAI_API_KEYS: OPENAI_API_KEYS,
				OPENAI_API_CONFIGS: OPENAI_API_CONFIGS
			}).catch((error) => {
				toast.error(`${error}`);
			});

			if (res) {
				toast.success($i18n.t('OpenAI API settings updated'));
				await models.set(await getModels());
			}
		}
	};


	const updateConnectionsHandler = async () => {
		const res = await setConnectionsConfig(localStorage.token, connectionsConfig).catch((error) => {
			toast.error(`${error}`);
		});

		if (res) {
			toast.success($i18n.t('Connections settings updated'));
			await models.set(await getModels());
			await config.set(await getBackendConfig());
		}
	};

	const addOpenAIConnectionHandler = async (connection) => {
		OPENAI_API_BASE_URLS = [...OPENAI_API_BASE_URLS, connection.url];
		OPENAI_API_KEYS = [...OPENAI_API_KEYS, connection.key];
		OPENAI_API_CONFIGS[OPENAI_API_BASE_URLS.length - 1] = connection.config;

		await updateOpenAIHandler();
	};


	onMount(async () => {
		if ($user?.role === 'admin') {
			let openaiConfig = {};

			await Promise.all([
				(async () => {
					openaiConfig = await getOpenAIConfig(localStorage.token);
				})(),
				(async () => {
					connectionsConfig = await getConnectionsConfig(localStorage.token);
				})()
			]);

			ENABLE_OPENAI_API = openaiConfig.ENABLE_OPENAI_API;

			OPENAI_API_BASE_URLS = openaiConfig.OPENAI_API_BASE_URLS;
			OPENAI_API_KEYS = openaiConfig.OPENAI_API_KEYS;
			OPENAI_API_CONFIGS = openaiConfig.OPENAI_API_CONFIGS;

			if (ENABLE_OPENAI_API) {
				// get url and idx
				for (const [idx, url] of OPENAI_API_BASE_URLS.entries()) {
					if (!OPENAI_API_CONFIGS[idx]) {
						// Legacy support, url as key
						OPENAI_API_CONFIGS[idx] = OPENAI_API_CONFIGS[url] || {};
					}
				}

				OPENAI_API_BASE_URLS.forEach(async (url, idx) => {
					OPENAI_API_CONFIGS[idx] = OPENAI_API_CONFIGS[idx] || {};
					if (!(OPENAI_API_CONFIGS[idx]?.enable ?? true)) {
						return;
					}
					const res = await getOpenAIModels(localStorage.token, idx);
					if (res.pipelines) {
						pipelineUrls[url] = true;
					}
				});
			}

		}
	});

	const submitHandler = async () => {
		updateOpenAIHandler();

		dispatch('save');

		await config.set(await getBackendConfig());
	};
</script>

<AddConnectionModal
	bind:show={showAddOpenAIConnectionModal}
	onSubmit={addOpenAIConnectionHandler}
/>

<form class="flex flex-col h-full justify-between text-sm" on:submit|preventDefault={submitHandler}>
	<div class=" overflow-y-scroll scrollbar-hidden h-full">
		{#if ENABLE_OPENAI_API !== null && connectionsConfig !== null}
			<div class="mb-3.5">
				<div class=" mb-2.5 text-base font-medium">{$i18n.t('General')}</div>

				<hr class=" border-gray-100 dark:border-gray-850 my-2" />

				<div class="my-2">
					<div class="mt-2 space-y-2">
						<div class="flex justify-between items-center text-sm">
							<div class="  font-medium">{$i18n.t('OpenAI API')}</div>

							<div class="flex items-center">
								<div class="">
									<Switch
										bind:state={ENABLE_OPENAI_API}
										on:change={async () => {
											updateOpenAIHandler();
										}}
									/>
								</div>
							</div>
						</div>

						{#if ENABLE_OPENAI_API}
							<div class="">
								<div class="flex justify-between items-center">
									<div class="font-medium text-xs">{$i18n.t('Manage OpenAI API Connections')}</div>

									<Tooltip content={$i18n.t(`Add Connection`)}>
										<button
											class="px-1"
											on:click={() => {
												showAddOpenAIConnectionModal = true;
											}}
											type="button"
										>
											<Plus />
										</button>
									</Tooltip>
								</div>

								<div class="flex flex-col gap-1.5 mt-1.5">
									{#each OPENAI_API_BASE_URLS as url, idx}
										<OpenAIConnection
											bind:url={OPENAI_API_BASE_URLS[idx]}
											bind:key={OPENAI_API_KEYS[idx]}
											bind:config={OPENAI_API_CONFIGS[idx]}
											pipeline={pipelineUrls[url] ? true : false}
											onSubmit={() => {
												updateOpenAIHandler();
											}}
											onDelete={() => {
												OPENAI_API_BASE_URLS = OPENAI_API_BASE_URLS.filter(
													(url, urlIdx) => idx !== urlIdx
												);
												OPENAI_API_KEYS = OPENAI_API_KEYS.filter((key, keyIdx) => idx !== keyIdx);

												let newConfig = {};
												OPENAI_API_BASE_URLS.forEach((url, newIdx) => {
													newConfig[newIdx] =
														OPENAI_API_CONFIGS[newIdx < idx ? newIdx : newIdx + 1];
												});
												OPENAI_API_CONFIGS = newConfig;
												updateOpenAIHandler();
											}}
										/>
									{/each}
								</div>
							</div>
						{/if}
					</div>
				</div>

				<div class="my-2">
					<div class="flex justify-between items-center text-sm">
						<div class="  font-medium">{$i18n.t('Direct Connections')}</div>

						<div class="flex items-center">
							<div class="">
								<Switch
									bind:state={connectionsConfig.ENABLE_DIRECT_CONNECTIONS}
									on:change={async () => {
										updateConnectionsHandler();
									}}
								/>
							</div>
						</div>
					</div>

					<div class="mt-1 text-xs text-gray-400 dark:text-gray-500">
						{$i18n.t(
							'Direct Connections allow users to connect to their own OpenAI compatible API endpoints.'
						)}
					</div>
				</div>

				<hr class=" border-gray-100 dark:border-gray-850 my-2" />

				<div class="my-2">
					<div class="flex justify-between items-center text-sm">
						<div class=" text-xs font-medium">{$i18n.t('Cache Base Model List')}</div>

						<div class="flex items-center">
							<div class="">
								<Switch
									bind:state={connectionsConfig.ENABLE_BASE_MODELS_CACHE}
									on:change={async () => {
										updateConnectionsHandler();
									}}
								/>
							</div>
						</div>
					</div>

					<div class="mt-1 text-xs text-gray-400 dark:text-gray-500">
						{$i18n.t(
							'Base Model List Cache speeds up access by fetching base models only at startup or on settings save—faster, but may not show recent base model changes.'
						)}
					</div>
				</div>
			</div>
		{:else}
			<div class="flex h-full justify-center">
				<div class="my-auto">
					<Spinner className="size-6" />
				</div>
			</div>
		{/if}
	</div>

	<div class="flex justify-end pt-3 text-sm font-medium">
		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			type="submit"
		>
			{$i18n.t('Save')}
		</button>
	</div>
</form>
