// src/lib/components/admin/Settings/Connections.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { createEventDispatcher, onMount, getContext, tick } from 'svelte';

	const dispatch = createEventDispatcher();

	import { getOpenAIConfig, updateOpenAIConfig, getOpenAIModels } from '$lib/apis/openai';
	import { getModels as _getModels, getBackendConfig } from '$lib/apis';
	import { getConnectionsConfig, setConnectionsConfig } from '$lib/apis/configs';

	import { config, models, settings, user } from '$lib/stores';

	import Switch from '$lib/components/common/Switch.svelte';
	import Spinner from '$lib/components/common/Spinner.svelte';
	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import Plus from '$lib/components/icons/Plus.svelte';

	import OpenAIConnection from './Connections/OpenAIConnection.svelte';
	import AddConnectionModal from '$lib/components/AddConnectionModal.svelte';

	const i18n = getContext('i18n');

	const getModels = async () => {
		const models = await _getModels(
			localStorage.token,
			$config?.features?.enable_direct_connections && ($settings?.directConnections ?? null),
			false,
			true
		);
		return models;
	};

	// External
	let OPENAI_API_KEYS = [''];
	let OPENAI_API_BASE_URLS = [''];
	let OPENAI_API_CONFIGS = {};

	let ENABLE_OPENAI_API: null | boolean = null;

	let connectionsConfig = null;

	let pipelineUrls = {};
	let showAddOpenAIConnectionModal = false;

	const updateOpenAIHandler = async () => {
		if (ENABLE_OPENAI_API !== null) {
			// Remove trailing slashes
			OPENAI_API_BASE_URLS = OPENAI_API_BASE_URLS.map((url) => url.replace(/\/$/, ''));

			// Check if API KEYS length is same than API URLS length
			if (OPENAI_API_KEYS.length !== OPENAI_API_BASE_URLS.length) {
				// if there are more keys than urls, remove the extra keys
				if (OPENAI_API_KEYS.length > OPENAI_API_BASE_URLS.length) {
					OPENAI_API_KEYS = OPENAI_API_KEYS.slice(0, OPENAI_API_BASE_URLS.length);
				}

				// if there are more urls than keys, add empty keys
				if (OPENAI_API_KEYS.length < OPENAI_API_BASE_URLS.length) {
					const diff = OPENAI_API_BASE_URLS.length - OPENAI_API_KEYS.length;
					for (let i = 0; i < diff; i++) {
						OPENAI_API_KEYS.push('');
					}
				}
			}

			const res = await updateOpenAIConfig(localStorage.token, {
				ENABLE_OPENAI_API: ENABLE_OPENAI_API,
				OPENAI_API_BASE_URLS: OPENAI_API_BASE_URLS,
				OPENAI_API_KEYS: OPENAI_API_KEYS,
				OPENAI_API_CONFIGS: OPENAI_API_CONFIGS
			}).catch((error) => {
				toast.error(`${error}`);
			});

			if (res) {
				toast.success($i18n.t('OpenAI API settings updated'));
				await models.set(await getModels());
			}
		}
	};


	const updateConnectionsHandler = async () => {
		const res = await setConnectionsConfig(localStorage.token, connectionsConfig).catch((error) => {
			toast.error(`${error}`);
		});

		if (res) {
			toast.success($i18n.t('Connections settings updated'));
			await models.set(await getModels());
			await config.set(await getBackendConfig());
		}
	};

	const addOpenAIConnectionHandler = async (connection) => {
		OPENAI_API_BASE_URLS = [...OPENAI_API_BASE_URLS, connection.url];
		OPENAI_API_KEYS = [...OPENAI_API_KEYS, connection.key];
		OPENAI_API_CONFIGS[OPENAI_API_BASE_URLS.length - 1] = connection.config;

		await updateOpenAIHandler();
	};


	onMount(async () => {
		if ($user?.role === 'admin') {
			let openaiConfig = {};

			await Promise.all([
				(async () => {
					openaiConfig = await getOpenAIConfig(localStorage.token);
				})(),
				(async () => {
					connectionsConfig = await getConnectionsConfig(localStorage.token);
				})()
			]);

			ENABLE_OPENAI_API = openaiConfig.ENABLE_OPENAI_API;

			OPENAI_API_BASE_URLS = openaiConfig.OPENAI_API_BASE_URLS;
			OPENAI_API_KEYS = openaiConfig.OPENAI_API_KEYS;
			OPENAI_API_CONFIGS = openaiConfig.OPENAI_API_CONFIGS;

			if (ENABLE_OPENAI_API) {
				// get url and idx
				for (const [idx, url] of OPENAI_API_BASE_URLS.entries()) {
					if (!OPENAI_API_CONFIGS[idx]) {
						// Legacy support, url as key
						OPENAI_API_CONFIGS[idx] = OPENAI_API_CONFIGS[url] || {};
					}
				}

				OPENAI_API_BASE_URLS.forEach(async (url, idx) => {
					OPENAI_API_CONFIGS[idx] = OPENAI_API_CONFIGS[idx] || {};
					if (!(OPENAI_API_CONFIGS[idx]?.enable ?? true)) {
						return;
					}
					const res = await getOpenAIModels(localStorage.token, idx);
					if (res.pipelines) {
						pipelineUrls[url] = true;
					}
				});
			}

		}
	});

	const submitHandler = async () => {
		updateOpenAIHandler();

		dispatch('save');

		await config.set(await getBackendConfig());
	};
</script>

<AddConnectionModal
	bind:show={showAddOpenAIConnectionModal}
	onSubmit={addOpenAIConnectionHandler}
/>

<form class="flex flex-col h-full justify-between text-sm" on:submit|preventDefault={submitHandler}>
	<div class=" overflow-y-scroll scrollbar-hidden h-full">
		{#if ENABLE_OPENAI_API !== null && connectionsConfig !== null}
			<div class="mb-3.5">
				<div class=" mb-2.5 text-base font-medium">{$i18n.t('General')}</div>

				<hr class=" border-gray-100 dark:border-gray-850 my-2" />

				<div class="my-2">
					<div class="mt-2 space-y-2">
						<div class="flex justify-between items-center text-sm">
							<div class="  font-medium">{$i18n.t('OpenAI API')}</div>

							<div class="flex items-center">
								<div class="">
									<Switch
										bind:state={ENABLE_OPENAI_API}
										on:change={async () => {
											updateOpenAIHandler();
										}}
									/>
								</div>
							</div>
						</div>

						{#if ENABLE_OPENAI_API}
							<div class="">
								<div class="flex justify-between items-center">
									<div class="font-medium text-xs">{$i18n.t('Manage OpenAI API Connections')}</div>

									<Tooltip content={$i18n.t(`Add Connection`)}>
										<button
											class="px-1"
											on:click={() => {
												showAddOpenAIConnectionModal = true;
											}}
											type="button"
										>
											<Plus />
										</button>
									</Tooltip>
								</div>

								<div class="flex flex-col gap-1.5 mt-1.5">
									{#each OPENAI_API_BASE_URLS as url, idx}
										<OpenAIConnection
											bind:url={OPENAI_API_BASE_URLS[idx]}
											bind:key={OPENAI_API_KEYS[idx]}
											bind:config={OPENAI_API_CONFIGS[idx]}
											pipeline={pipelineUrls[url] ? true : false}
											onSubmit={() => {
												updateOpenAIHandler();
											}}
											onDelete={() => {
												OPENAI_API_BASE_URLS = OPENAI_API_BASE_URLS.filter(
													(url, urlIdx) => idx !== urlIdx
												);
												OPENAI_API_KEYS = OPENAI_API_KEYS.filter((key, keyIdx) => idx !== keyIdx);

												let newConfig = {};
												OPENAI_API_BASE_URLS.forEach((url, newIdx) => {
													newConfig[newIdx] =
														OPENAI_API_CONFIGS[newIdx < idx ? newIdx : newIdx + 1];
												});
												OPENAI_API_CONFIGS = newConfig;
												updateOpenAIHandler();
											}}
										/>
									{/each}
								</div>
							</div>
						{/if}
					</div>
				</div>

				<div class="my-2">
					<div class="flex justify-between items-center text-sm">
						<div class="  font-medium">{$i18n.t('Direct Connections')}</div>

						<div class="flex items-center">
							<div class="">
								<Switch
									bind:state={connectionsConfig.ENABLE_DIRECT_CONNECTIONS}
									on:change={async () => {
										updateConnectionsHandler();
									}}
								/>
							</div>
						</div>
					</div>

					<div class="mt-1 text-xs text-gray-400 dark:text-gray-500">
						{$i18n.t(
							'Direct Connections allow users to connect to their own OpenAI compatible API endpoints.'
						)}
					</div>
				</div>

				<hr class=" border-gray-100 dark:border-gray-850 my-2" />

				<div class="my-2">
					<div class="flex justify-between items-center text-sm">
						<div class=" text-xs font-medium">{$i18n.t('Cache Base Model List')}</div>

						<div class="flex items-center">
							<div class="">
								<Switch
									bind:state={connectionsConfig.ENABLE_BASE_MODELS_CACHE}
									on:change={async () => {
										updateConnectionsHandler();
									}}
								/>
							</div>
						</div>
					</div>

					<div class="mt-1 text-xs text-gray-400 dark:text-gray-500">
						{$i18n.t(
							'Base Model List Cache speeds up access by fetching base models only at startup or on settings save—faster, but may not show recent base model changes.'
						)}
					</div>
				</div>
			</div>
		{:else}
			<div class="flex h-full justify-center">
				<div class="my-auto">
					<Spinner className="size-6" />
				</div>
			</div>
		{/if}
	</div>

	<div class="flex justify-end pt-3 text-sm font-medium">
		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			type="submit"
		>
			{$i18n.t('Save')}
		</button>
	</div>
</form>

// src/components/chat/Settings/Connections.tsx
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Plus } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { useAppStore } from '@/store';
import AddConnectionModal from '@/components/admin/AddConnectionModal';

interface Connection {
  url: string;
  key: string;
  config?: Record<string, unknown>;
}

interface ConnectionsProps {
  saveSettings: (settings: Record<string, unknown>) => Promise<void>;
}

export default function Connections({ saveSettings }: ConnectionsProps) {
  const { t } = useTranslation();
  const { settings } = useAppStore();

  const [config, setConfig] = useState<any>(null);
  const [showConnectionModal, setShowConnectionModal] = useState(false);
  const [editingConnection, setEditingConnection] = useState<Connection | null>(null);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);

  useEffect(() => {
    setConfig(
      settings?.directConnections ?? {
        OPENAI_API_BASE_URLS: [],
        OPENAI_API_KEYS: [],
        OPENAI_API_CONFIGS: {},
      }
    );
  }, [settings]);

  const addConnectionHandler = async (connection: Connection) => {
    const newConfig = { ...config };
    newConfig.OPENAI_API_BASE_URLS.push(connection.url);
    newConfig.OPENAI_API_KEYS.push(connection.key);
    newConfig.OPENAI_API_CONFIGS[newConfig.OPENAI_API_BASE_URLS.length - 1] = connection.config;

    setConfig(newConfig);
    await updateHandler(newConfig);
    setShowConnectionModal(false);
  };

  const updateConnectionHandler = async (connection: Connection) => {
    if (editingIndex === null) return;

    const newConfig = { ...config };
    newConfig.OPENAI_API_BASE_URLS[editingIndex] = connection.url;
    newConfig.OPENAI_API_KEYS[editingIndex] = connection.key;
    newConfig.OPENAI_API_CONFIGS[editingIndex] = connection.config;

    setConfig(newConfig);
    await updateHandler(newConfig);
    setShowConnectionModal(false);
    setEditingConnection(null);
    setEditingIndex(null);
  };

  const deleteConnectionHandler = async (index: number) => {
    const newConfig = { ...config };
    newConfig.OPENAI_API_BASE_URLS = newConfig.OPENAI_API_BASE_URLS.filter(
      (_: string, idx: number) => idx !== index
    );
    newConfig.OPENAI_API_KEYS = newConfig.OPENAI_API_KEYS.filter(
      (_: string, idx: number) => idx !== index
    );

    const newConfigs: Record<string, any> = {};
    newConfig.OPENAI_API_BASE_URLS.forEach((url: string, newIdx: number) => {
      newConfigs[newIdx] = newConfig.OPENAI_API_CONFIGS[newIdx < index ? newIdx : newIdx + 1];
    });
    newConfig.OPENAI_API_CONFIGS = newConfigs;

    setConfig(newConfig);
    await updateHandler(newConfig);
  };

  const updateHandler = async (updatedConfig: Record<string, unknown>) => {
    // Remove trailing slashes
    updatedConfig.OPENAI_API_BASE_URLS = updatedConfig.OPENAI_API_BASE_URLS.map((url: string) =>
      url.replace(/\/$/, '')
    );

    // Check if API KEYS length is same as API URLS length
    if (updatedConfig.OPENAI_API_KEYS.length !== updatedConfig.OPENAI_API_BASE_URLS.length) {
      // if there are more keys than urls, remove the extra keys
      if (updatedConfig.OPENAI_API_KEYS.length > updatedConfig.OPENAI_API_BASE_URLS.length) {
        updatedConfig.OPENAI_API_KEYS = updatedConfig.OPENAI_API_KEYS.slice(
          0,
          updatedConfig.OPENAI_API_BASE_URLS.length
        );
      }

      // if there are more urls than keys, add empty keys
      if (updatedConfig.OPENAI_API_KEYS.length < updatedConfig.OPENAI_API_BASE_URLS.length) {
        const diff = updatedConfig.OPENAI_API_BASE_URLS.length - updatedConfig.OPENAI_API_KEYS.length;
        for (let i = 0; i < diff; i++) {
          updatedConfig.OPENAI_API_KEYS.push('');
        }
      }
    }

    await saveSettings({
      directConnections: updatedConfig,
    });
  };

  const openEditModal = (index: number) => {
    const connection: Connection = {
      url: config.OPENAI_API_BASE_URLS[index],
      key: config.OPENAI_API_KEYS[index],
      config: config.OPENAI_API_CONFIGS[index] || {},
    };
    setEditingIndex(index);
    setEditingConnection(connection);
    setShowConnectionModal(true);
  };

  if (!config) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground">{t('Loading...')}</div>
      </div>
    );
  }

  return (
    <TooltipProvider>
      <>
        <AddConnectionModal
          open={showConnectionModal}
          onOpenChange={(open) => {
            if (!open) {
              setShowConnectionModal(false);
              setEditingConnection(null);
              setEditingIndex(null);
            }
          }}
          onSubmit={editingIndex !== null ? updateConnectionHandler : addConnectionHandler}
          onDelete={
            editingIndex !== null
              ? () => {
                  deleteConnectionHandler(editingIndex);
                  setShowConnectionModal(false);
                  setEditingConnection(null);
                  setEditingIndex(null);
                }
              : undefined
          }
          connection={editingConnection}
          edit={editingIndex !== null}
          direct={true}
        />

        <div className="flex flex-col h-full text-sm">
          <div className="overflow-y-auto h-full">
            <div className="pr-1.5">
              <div className="flex justify-between items-center mb-2">
                <div className="font-medium">{t('Manage Direct Connections')}</div>

                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => {
                        setEditingConnection(null);
                        setEditingIndex(null);
                        setShowConnectionModal(true);
                      }}
                    >
                      <Plus className="h-4 w-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>{t('Add Connection')}</p>
                  </TooltipContent>
                </Tooltip>
              </div>

              <div className="space-y-2">
                {config?.OPENAI_API_BASE_URLS?.length > 0 ? (
                  config.OPENAI_API_BASE_URLS.map((url: string, idx: number) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between p-3 border rounded-lg hover:bg-accent/50 transition"
                    >
                      <div className="flex-1 min-w-0">
                        <div className="text-sm font-medium truncate">{url}</div>
                        <div className="text-xs text-muted-foreground truncate">
                          {config.OPENAI_API_CONFIGS[idx]?.prefix_id || t('No prefix')}
                        </div>
                      </div>
                      <div className="flex gap-2 ml-4">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => openEditModal(idx)}
                        >
                          {t('Edit')}
                        </Button>
                        <Button
                          variant="destructive"
                          size="sm"
                          onClick={() => deleteConnectionHandler(idx)}
                        >
                          {t('Delete')}
                        </Button>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    {t('No connections configured')}
                  </div>
                )}
              </div>

              <div className="mt-4 text-xs text-gray-500">
                {t('Connect to your own OpenAI compatible API endpoints.')}
                <br />
                {t(
                  'CORS must be properly configured by the provider to allow requests from Open WebUI.'
                )}
              </div>
            </div>
          </div>
        </div>
      </>
    </TooltipProvider>
  );
}
