// src/components/chat/CodeBlock.tsx
import { useState, useEffect, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { ChevronUp, ChevronDown, Copy, Check, Play } from 'lucide-react';
import { toast } from 'sonner';
import hljs from 'highlight.js';
import 'highlight.js/styles/github-dark.css';
import { executeCode } from '@/lib/apis/utils';
import { useAppStore } from '@/store';
import CodeEditor from './CodeEditor';

interface CodeBlockProps {
  language: string;
  code: string;
  collapsible?: boolean;
  editable?: boolean;
  onSave?: (code: string) => void;
  className?: string;
  id: string;
}

export default function CodeBlock({
  language,
  code: initialCode,
  collapsible = true,
  editable = false,
  onSave,
  className = '',
  id = ''
}: CodeBlockProps) {
  const [collapsed, setCollapsed] = useState(false);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const [executing, setExecuting] = useState(false);
  const [code, setCode] = useState(initialCode);
  const [stdout, setStdout] = useState<string | null>(null);
  const [stderr, setStderr] = useState<string | null>(null);
  const [result, setResult] = useState<any>(null);
  const [files, setFiles] = useState<any[]>([]);
  const codeRef = useRef<HTMLElement>(null);
  const preRef = useRef<HTMLPreElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const user = useAppStore(state => state.user);
  const token = user?.token || (typeof localStorage !== 'undefined' ? localStorage.getItem('token') : null);

  useEffect(() => {
    setCode(initialCode);
  }, [initialCode]);

  useEffect(() => {
    if (codeRef.current && preRef.current && !collapsed && !editable) {
      // Use hljs.highlight to match Svelte exactly
      try {
        const highlighted = language 
          ? hljs.highlight(code, { language: language, ignoreIllegals: true })
          : hljs.highlightAuto(code);
        
        codeRef.current.innerHTML = highlighted.value;

        // Add line numbers
        const lines = code.split('\n');
        const lineNumbersDiv = document.createElement('div');
        lineNumbersDiv.className = 'line-numbers-rows';
        lineNumbersDiv.style.cssText = `
          position: absolute;
          pointer-events: none;
          top: 1rem;
          left: 0;
          width: 3em;
          font-size: 100%;
          text-align: right;
          padding-right: 0.8em;
          user-select: none;
          counter-reset: linenumber;
        `;

        lines.forEach((_, idx) => {
          const lineDiv = document.createElement('div');
          lineDiv.textContent = String(idx + 1);
          lineDiv.style.cssText = `
            display: block;
            counter-increment: linenumber;
            color: #999;
            line-height: 1.5;
            font-family: monospace;
          `;
          lineNumbersDiv.appendChild(lineDiv);
        });

        // Remove old line numbers if they exist
        const oldLineNumbers = preRef.current.querySelector('.line-numbers-rows');
        if (oldLineNumbers) {
          oldLineNumbers.remove();
        }

        preRef.current.appendChild(lineNumbersDiv);
      } catch (e) {
        console.error('Error highlighting code:', e);
        codeRef.current.textContent = code;
      }
    }
  }, [code, collapsed, editable, language]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      toast.success('Code copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy code');
    }
  };

  const handleSave = () => {
    if (onSave) {
      onSave(code);
      setSaved(true);
      toast.success('Code saved');
      setTimeout(() => setSaved(false), 2000);
    }
  };

  const handleExecute = async () => {
    if (!['python', 'py'].includes(language.toLowerCase())) {
      toast.error('Code execution only supports Python');
      return;
    }

    if (!token) {
      toast.error('Please log in to execute code');
      return;
    }

    setExecuting(true);
    setStdout(null);
    setStderr(null);
    setResult(null);
    setFiles([]);

    try {
      const response = await executeCode(token, code);
      
      if (response.stdout) {
        setStdout(response.stdout);
      }
      if (response.stderr) {
        setStderr(response.stderr);
      }
      if (response.result) {
        setResult(response.result);
      }
      if (response.files) {
        setFiles(response.files);
      }

      toast.success('Code executed successfully');
    } catch (error: any) {
      toast.error(error.message || 'Failed to execute code');
      setStderr(error.message || 'Execution failed');
    } finally {
      setExecuting(false);
    }
  };

  const toggleCollapse = () => {
    setCollapsed(!collapsed);
  };

  const lineCount = code.split('\n').length;

  // Check if it's Python code
  const isPython = ['python', 'py'].includes(language.toLowerCase()) || 
                   (language === '' && /^(import |from |def |class |print\()/m.test(code));

  return (
    <div className={`relative flex flex-col rounded-3xl border border-gray-200 dark:border-gray-800 my-2 ${className}`}>
      {/* Language label */}
      <div className="absolute left-0 top-0 py-2.5 px-4 text-xs font-medium text-gray-500 dark:text-gray-400">
        {language || 'plaintext'}
      </div>

      {/* Action buttons */}
      <div className="sticky top-0 left-0 right-0 py-2 pr-3 flex items-center justify-end w-full z-10 text-xs">
        <div className="flex items-center gap-0.5">
          {/* Collapse/Expand button */}
          {collapsible && (
            <Button
              variant="ghost"
              size="sm"
              onClick={toggleCollapse}
              className="h-7 px-2 gap-1 bg-white dark:bg-black hover:bg-gray-100 dark:hover:bg-gray-900 rounded-md"
            >
              {collapsed ? (
                <>
                  <ChevronDown className="h-3 w-3" />
                  <span>Expand</span>
                </>
              ) : (
                <>
                  <ChevronUp className="h-3 w-3" />
                  <span>Collapse</span>
                </>
              )}
            </Button>
          )}

          {/* Run button for Python */}
          {isPython && (
            <Button
              variant="ghost"
              size="sm"
              onClick={handleExecute}
              disabled={executing}
              className="h-7 px-2 gap-1 bg-white dark:bg-black hover:bg-gray-100 dark:hover:bg-gray-900 rounded-md"
            >
              <Play className="h-3 w-3" />
              <span>{executing ? 'Running' : 'Run'}</span>
            </Button>
          )}

          {/* Save button */}
          {editable && onSave && (
            <Button
              variant="ghost"
              size="sm"
              onClick={handleSave}
              className="h-7 px-2 bg-white dark:bg-black hover:bg-gray-100 dark:hover:bg-gray-900 rounded-md"
            >
              <span>{saved ? 'Saved' : 'Save'}</span>
            </Button>
          )}

          {/* Copy button */}
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCopy}
            className="h-7 px-2 bg-white dark:bg-black hover:bg-gray-100 dark:hover:bg-gray-900 rounded-md"
          >
            {copied ? (
              <>
                <Check className="h-3 w-3 mr-1" />
                <span>Copied</span>
              </>
            ) : (
              <>
                <Copy className="h-3 w-3 mr-1" />
                <span>Copy</span>
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Code content */}
      <div className={`language-${language} rounded-t-3xl -mt-9 overflow-hidden ${
        executing || stdout || stderr || result ? '' : 'rounded-b-3xl'
      }`}>
        <div className="pt-8 bg-white dark:bg-black"></div>

        {!collapsed && (
          <>
            {editable ? (
              <CodeEditor
                value={code}
                id={id}
                lang={language}
                onChange={(value) => setCode(value)}
                onSave={handleSave}
              />
            ) : (
              <pre 
                ref={preRef}
                className="hljs p-4 overflow-x-auto m-0 relative" 
                style={{ 
                  borderTopLeftRadius: 0, 
                  borderTopRightRadius: 0,
                  paddingLeft: '3.5rem',
                  ...(executing || stdout || stderr || result ? {
                    borderBottomLeftRadius: 0,
                    borderBottomRightRadius: 0
                  } : {})
                }}
              >
                <code
                  ref={codeRef}
                  className={`language-${language} rounded-t-none whitespace-pre text-sm block`}
                  style={{ lineHeight: '1.5' }}
                >
                  {code}
                </code>
              </pre>
            )}
          </>
        )}

        {collapsed && (
          <div className="bg-white dark:bg-black dark:text-white rounded-b-3xl pt-0.5 pb-3 px-4 flex flex-col gap-2 text-xs">
            <span className="text-gray-500 italic">
              {lineCount} hidden {lineCount === 1 ? 'line' : 'lines'}
            </span>
          </div>
        )}
      </div>

      {/* Execution results */}
      {!collapsed && (executing || stdout || stderr || result || files.length > 0) && (
        <div className="bg-gray-50 dark:bg-black dark:text-white rounded-b-3xl py-4 px-4 flex flex-col gap-2">
          {executing && (
            <div>
              <div className="text-gray-500 text-xs mb-1">STDOUT/STDERR</div>
              <div className="text-sm">Running...</div>
            </div>
          )}

          {stdout && (
            <div>
              <div className="text-gray-500 text-xs mb-1">STDOUT</div>
              <pre className="text-sm whitespace-pre-wrap font-mono">{stdout}</pre>
            </div>
          )}

          {stderr && (
            <div>
              <div className="text-red-500 text-xs mb-1">STDERR</div>
              <pre className="text-sm whitespace-pre-wrap font-mono text-red-500">{stderr}</pre>
            </div>
          )}

          {result && (
            <div>
              <div className="text-gray-500 text-xs mb-1">RESULT</div>
              <pre className="text-sm whitespace-pre-wrap font-mono">{JSON.stringify(result, null, 2)}</pre>
            </div>
          )}

          {files.length > 0 && (
            <div>
              <div className="text-gray-500 text-xs mb-1">FILES</div>
              <div className="flex flex-col gap-2">
                {files.map((file, idx) => (
                  <a
                    key={idx}
                    href={file.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-sm text-blue-500 hover:underline"
                  >
                    {file.name}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// src/lib/components/chat/Messages/CodeBlock.svelte
<script lang="ts">
	import hljs from 'highlight.js';
	import { toast } from 'svelte-sonner';
	import { getContext, onMount, tick, onDestroy } from 'svelte';
	import { config } from '$lib/stores';

	import { executeCode } from '$lib/apis/utils';
	import { copyToClipboard, renderMermaidDiagram } from '$lib/utils';

	import 'highlight.js/styles/github-dark.min.css';

	import CodeEditor from '$lib/components/common/CodeEditor.svelte';
	import SvgPanZoom from '$lib/components/common/SVGPanZoom.svelte';

	import ChevronUp from '$lib/components/icons/ChevronUp.svelte';
	import ChevronUpDown from '$lib/components/icons/ChevronUpDown.svelte';
	import CommandLine from '$lib/components/icons/CommandLine.svelte';
	import Cube from '$lib/components/icons/Cube.svelte';

	const i18n = getContext('i18n');

	export let id = '';
	export let edit = true;

	export let onSave = (e) => {};
	export let onUpdate = (e) => {};
	export let onPreview = (e) => {};

	export let save = false;
	export let run = true;
	export let preview = false;
	export let collapsed = false;

	export let token;
	export let lang = '';
	export let code = '';
	export let attributes = {};

	export let className = 'mb-2';
	export let editorClassName = '';
	export let stickyButtonsClassName = 'top-0';

	let _code = '';
	$: if (code) {
		updateCode();
	}

	const updateCode = () => {
		_code = code;
	};

	let _token = null;

	let mermaidHtml = null;

	let highlightedCode = null;
	let executing = false;

	let stdout = null;
	let stderr = null;
	let result = null;
	let files = null;

	let copied = false;
	let saved = false;

	const collapseCodeBlock = () => {
		collapsed = !collapsed;
	};

	const saveCode = () => {
		saved = true;

		code = _code;
		onSave(code);

		setTimeout(() => {
			saved = false;
		}, 1000);
	};

	const copyCode = async () => {
		copied = true;
		await copyToClipboard(_code);

		setTimeout(() => {
			copied = false;
		}, 1000);
	};

	const previewCode = () => {
		onPreview(code);
	};

	const checkPythonCode = (str) => {
		// Check if the string contains typical Python syntax characters
		const pythonSyntax = [
			'def ',
			'else:',
			'elif ',
			'try:',
			'except:',
			'finally:',
			'yield ',
			'lambda ',
			'assert ',
			'nonlocal ',
			'del ',
			'True',
			'False',
			'None',
			' and ',
			' or ',
			' not ',
			' in ',
			' is ',
			' with '
		];

		for (let syntax of pythonSyntax) {
			if (str.includes(syntax)) {
				return true;
			}
		}

		// If none of the above conditions met, it's probably not Python code
		return false;
	};

	const executePython = async (code) => {
		result = null;
		stdout = null;
		stderr = null;

		executing = true;

		const output = await executeCode(localStorage.token, code).catch((error) => {
			toast.error(`${error}`);
			return null;
		});

		if (output) {
			if (output['stdout']) {
				stdout = output['stdout'];
				const stdoutLines = stdout.split('\n');

				for (const [idx, line] of stdoutLines.entries()) {
					if (line.startsWith('data:image/png;base64')) {
						if (files) {
							files.push({
								type: 'image/png',
								data: line
							});
						} else {
							files = [
								{
									type: 'image/png',
									data: line
								}
							];
						}

						if (stdout.includes(`${line}\n`)) {
							stdout = stdout.replace(`${line}\n`, ``);
						} else if (stdout.includes(`${line}`)) {
							stdout = stdout.replace(`${line}`, ``);
						}
					}
				}
			}

			if (output['result']) {
				result = output['result'];
				const resultLines = result.split('\n');

				for (const [idx, line] of resultLines.entries()) {
					if (line.startsWith('data:image/png;base64')) {
						if (files) {
							files.push({
								type: 'image/png',
								data: line
							});
						} else {
							files = [
								{
									type: 'image/png',
									data: line
								}
							];
						}

						if (result.includes(`${line}\n`)) {
							result = result.replace(`${line}\n`, ``);
						} else if (result.includes(`${line}`)) {
							result = result.replace(`${line}`, ``);
						}
					}
				}
			}

			output['stderr'] && (stderr = output['stderr']);
		}

		executing = false;
	};

	const render = async () => {
		onUpdate(token);
		if (lang === 'mermaid' && (token?.raw ?? '').slice(-4).includes('```')) {
			mermaidHtml = await renderMermaidDiagram(code);
		}
	};

	$: if (token) {
		if (JSON.stringify(token) !== JSON.stringify(_token)) {
			_token = token;
		}
	}

	$: if (_token) {
		render();
	}

	$: if (attributes) {
		onAttributesUpdate();
	}

	const onAttributesUpdate = () => {
		if (attributes?.output) {
			// Create a helper function to unescape HTML entities
			const unescapeHtml = (html) => {
				const textArea = document.createElement('textarea');
				textArea.innerHTML = html;
				return textArea.value;
			};

			try {
				// Unescape the HTML-encoded string
				const unescapedOutput = unescapeHtml(attributes.output);

				// Parse the unescaped string into JSON
				const output = JSON.parse(unescapedOutput);

				// Assign the parsed values to variables
				stdout = output.stdout;
				stderr = output.stderr;
				result = output.result;
			} catch (error) {
				console.error('Error:', error);
			}
		}
	};

	onMount(async () => {
		if (token) {
			onUpdate(token);
		}
	});

	onDestroy(() => {});
</script>

<div>
	<div
		class="relative {className} flex flex-col rounded-3xl border border-gray-100 dark:border-gray-850 my-0.5"
		dir="ltr"
	>
		{#if lang === 'mermaid'}
			{#if mermaidHtml}
				<SvgPanZoom
					className=" rounded-3xl max-h-fit overflow-hidden"
					svg={mermaidHtml}
					content={_token.text}
				/>
			{:else}
				<pre class="mermaid">{code}</pre>
			{/if}
		{:else}
			<div
				class="absolute left-0 right-0 py-2.5 pr-3 text-text-300 pl-4.5 text-xs font-medium dark:text-white"
			>
				{lang}
			</div>

			<div
				class="sticky {stickyButtonsClassName} left-0 right-0 py-2 pr-3 flex items-center justify-end w-full z-10 text-xs text-black dark:text-white"
			>
				<div class="flex items-center gap-0.5">
					<button
						class="flex gap-1 items-center bg-none border-none transition rounded-md px-1.5 py-0.5 bg-white dark:bg-black"
						on:click={collapseCodeBlock}
					>
						<div class=" -translate-y-[0.5px]">
							<ChevronUpDown className="size-3" />
						</div>

						<div>
							{collapsed ? $i18n.t('Expand') : $i18n.t('Collapse')}
						</div>
					</button>

					{#if ($config?.features?.enable_code_execution ?? true) && (lang.toLowerCase() === 'python' || lang.toLowerCase() === 'py' || (lang === '' && checkPythonCode(code)))}
						{#if executing}
							<div
								class="run-code-button bg-none border-none p-0.5 cursor-not-allowed bg-white dark:bg-black"
							>
								{$i18n.t('Running')}
							</div>
						{:else if run}
							<button
								class="flex gap-1 items-center run-code-button bg-none border-none transition rounded-md px-1.5 py-0.5 bg-white dark:bg-black"
								on:click={async () => {
									code = _code;
									await tick();
									executePython(code);
								}}
							>
								<div>
									{$i18n.t('Run')}
								</div>
							</button>
						{/if}
					{/if}

					{#if save}
						<button
							class="save-code-button bg-none border-none transition rounded-md px-1.5 py-0.5 bg-white dark:bg-black"
							on:click={saveCode}
						>
							{saved ? $i18n.t('Saved') : $i18n.t('Save')}
						</button>
					{/if}

					<button
						class="copy-code-button bg-none border-none transition rounded-md px-1.5 py-0.5 bg-white dark:bg-black"
						on:click={copyCode}>{copied ? $i18n.t('Copied') : $i18n.t('Copy')}</button
					>

					{#if preview && ['html', 'svg'].includes(lang)}
						<button
							class="flex gap-1 items-center run-code-button bg-none border-none transition rounded-md px-1.5 py-0.5 bg-white dark:bg-black"
							on:click={previewCode}
						>
							<div>
								{$i18n.t('Preview')}
							</div>
						</button>
					{/if}
				</div>
			</div>

			<div
				class="language-{lang} rounded-t-3xl -mt-9 {editorClassName
					? editorClassName
					: executing || stdout || stderr || result
						? ''
						: 'rounded-b-3xl'} overflow-hidden"
			>
				<div class=" pt-8 bg-white dark:bg-black"></div>

				{#if !collapsed}
					{#if edit}
						<CodeEditor
							value={code}
							{id}
							{lang}
							onSave={() => {
								saveCode();
							}}
							onChange={(value) => {
								_code = value;
							}}
						/>
					{:else}
						<pre
							class=" hljs p-4 px-5 overflow-x-auto"
							style="border-top-left-radius: 0px; border-top-right-radius: 0px; {(executing ||
								stdout ||
								stderr ||
								result) &&
								'border-bottom-left-radius: 0px; border-bottom-right-radius: 0px;'}"><code
								class="language-{lang} rounded-t-none whitespace-pre text-sm"
								>{@html hljs.highlightAuto(code, hljs.getLanguage(lang)?.aliases).value ||
									code}</code
							></pre>
					{/if}
				{:else}
					<div
						class="bg-white dark:bg-black dark:text-white rounded-b-3xl! pt-0.5 pb-3 px-4 flex flex-col gap-2 text-xs"
					>
						<span class="text-gray-500 italic">
							{$i18n.t('{{COUNT}} hidden lines', {
								COUNT: code.split('\n').length
							})}
						</span>
					</div>
				{/if}
			</div>

			{#if !collapsed}
				<div
					id="plt-canvas-{id}"
					class="bg-gray-50 dark:bg-black dark:text-white max-w-full overflow-x-auto scrollbar-hidden"
				/>

				{#if executing || stdout || stderr || result || files}
					<div
						class="bg-gray-50 dark:bg-black dark:text-white rounded-b-3xl! py-4 px-4 flex flex-col gap-2"
					>
						{#if executing}
							<div class=" ">
								<div class=" text-gray-500 text-xs mb-1">{$i18n.t('STDOUT/STDERR')}</div>
								<div class="text-sm">{$i18n.t('Running...')}</div>
							</div>
						{:else}
							{#if stdout || stderr}
								<div class=" ">
									<div class=" text-gray-500 text-xs mb-1">{$i18n.t('STDOUT/STDERR')}</div>
									<div
										class="text-sm {stdout?.split('\n')?.length > 100
											? `max-h-96`
											: ''}  overflow-y-auto"
									>
										{stdout || stderr}
									</div>
								</div>
							{/if}
							{#if result || files}
								<div class=" ">
									<div class=" text-gray-500 text-xs mb-1">{$i18n.t('RESULT')}</div>
									{#if result}
										<div class="text-sm">{`${JSON.stringify(result)}`}</div>
									{/if}
									{#if files}
										<div class="flex flex-col gap-2">
											{#each files as file}
												{#if file.type.startsWith('image')}
													<img src={file.data} alt="Output" class=" w-full max-w-[36rem]" />
												{/if}
											{/each}
										</div>
									{/if}
								</div>
							{/if}
						{/if}
					</div>
				{/if}
			{/if}
		{/if}
	</div>
</div>
