// src/lib/components/admin/Settings/CodeExecution.svelte
<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { onMount, getContext } from 'svelte';
	import { getCodeExecutionConfig, setCodeExecutionConfig } from '$lib/apis/configs';

	import SensitiveInput from '$lib/components/common/SensitiveInput.svelte';

	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import Textarea from '$lib/components/common/Textarea.svelte';
	import Switch from '$lib/components/common/Switch.svelte';

	const i18n = getContext('i18n');

	export let saveHandler: Function;

	let config = null;

	let engines = ['jupyter', 'sandbox'];

	const submitHandler = async () => {
		const res = await setCodeExecutionConfig(localStorage.token, config);
	};

	onMount(async () => {
		const res = await getCodeExecutionConfig(localStorage.token);

		if (res) {
			config = res;
		}
	});
</script>

<form
	class="flex flex-col h-full justify-between space-y-3 text-sm"
	on:submit|preventDefault={async () => {
		await submitHandler();
		saveHandler();
	}}
>
	<div class=" space-y-3 overflow-y-scroll scrollbar-hidden h-full">
		{#if config}
			<div>
				<div class="mb-3.5">
					<div class=" mb-2.5 text-base font-medium">{$i18n.t('General')}</div>

					<hr class=" border-gray-100 dark:border-gray-850 my-2" />

					<div class="mb-2.5">
						<div class=" flex w-full justify-between">
							<div class=" self-center text-xs font-medium">
								{$i18n.t('Enable Code Execution')}
							</div>

							<Switch bind:state={config.ENABLE_CODE_EXECUTION} />
						</div>
					</div>

					<div class="mb-2.5">
						<div class="flex w-full justify-between">
							<div class=" self-center text-xs font-medium">{$i18n.t('Code Execution Engine')}</div>
							<div class="flex items-center relative">
								<select
									class="dark:bg-gray-900 w-fit pr-8 rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-right"
									bind:value={config.CODE_EXECUTION_ENGINE}
									placeholder={$i18n.t('Select a engine')}
									required
								>
									<option disabled selected value="">{$i18n.t('Select a engine')}</option>
									{#each engines as engine}
										<option value={engine}>{engine}</option>
									{/each}
								</select>
							</div>
						</div>

						{#if config.CODE_EXECUTION_ENGINE === 'jupyter'}
							<div class="text-gray-500 text-xs">
								{$i18n.t(
									'Warning: Jupyter execution enables arbitrary code execution, posing severe security risks—proceed with extreme caution.'
								)}
							</div>
						{:else if config.CODE_EXECUTION_ENGINE === 'sandbox'}
							<div class="text-gray-500 text-xs">
								{$i18n.t(
									'Sandbox executor provides isolated code execution with security restrictions.'
								)}
							</div>
						{/if}
					</div>

					{#if config.CODE_EXECUTION_ENGINE === 'jupyter'}
						<div class="mb-2.5 flex flex-col gap-1.5 w-full">
							<div class="text-xs font-medium">
								{$i18n.t('Jupyter URL')}
							</div>

							<div class="flex w-full">
								<div class="flex-1">
									<input
										class="w-full text-sm py-0.5 placeholder:text-gray-300 dark:placeholder:text-gray-700 bg-transparent outline-hidden"
										type="text"
										placeholder={$i18n.t('Enter Jupyter URL')}
										bind:value={config.CODE_EXECUTION_JUPYTER_URL}
										autocomplete="off"
									/>
								</div>
							</div>
						</div>

						<div class="mb-2.5 flex flex-col gap-1.5 w-full">
							<div class=" flex gap-2 w-full items-center justify-between">
								<div class="text-xs font-medium">
									{$i18n.t('Jupyter Auth')}
								</div>

								<div>
									<select
										class="dark:bg-gray-900 w-fit pr-8 rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-left"
										bind:value={config.CODE_EXECUTION_JUPYTER_AUTH}
										placeholder={$i18n.t('Select an auth method')}
									>
										<option selected value="">{$i18n.t('None')}</option>
										<option value="token">{$i18n.t('Token')}</option>
										<option value="password">{$i18n.t('Password')}</option>
									</select>
								</div>
							</div>

							{#if config.CODE_EXECUTION_JUPYTER_AUTH}
								<div class="flex w-full gap-2">
									<div class="flex-1">
										{#if config.CODE_EXECUTION_JUPYTER_AUTH === 'password'}
											<SensitiveInput
												type="text"
												placeholder={$i18n.t('Enter Jupyter Password')}
												bind:value={config.CODE_EXECUTION_JUPYTER_AUTH_PASSWORD}
												autocomplete="off"
											/>
										{:else}
											<SensitiveInput
												type="text"
												placeholder={$i18n.t('Enter Jupyter Token')}
												bind:value={config.CODE_EXECUTION_JUPYTER_AUTH_TOKEN}
												autocomplete="off"
											/>
										{/if}
									</div>
								</div>
							{/if}
						</div>

						<div class="flex gap-2 w-full items-center justify-between">
							<div class="text-xs font-medium">
								{$i18n.t('Code Execution Timeout')}
							</div>

							<div class="">
								<Tooltip content={$i18n.t('Enter timeout in seconds')}>
									<input
										class="dark:bg-gray-900 w-fit rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-right"
										type="number"
										bind:value={config.CODE_EXECUTION_JUPYTER_TIMEOUT}
										placeholder={$i18n.t('e.g. 60')}
										autocomplete="off"
									/>
								</Tooltip>
							</div>
						</div>
					{:else if config.CODE_EXECUTION_ENGINE === 'sandbox'}
						<div class="mb-2.5 flex flex-col gap-1.5 w-full">
							<div class="text-xs font-medium">
								{$i18n.t('Sandbox Executor URL')}
							</div>

							<div class="flex w-full">
								<div class="flex-1">
									<input
										class="w-full text-sm py-0.5 placeholder:text-gray-300 dark:placeholder:text-gray-700 bg-transparent outline-hidden"
										type="text"
										placeholder={$i18n.t('Enter Sandbox Executor URL (e.g. http://localhost:8090)')}
										bind:value={config.CODE_EXECUTION_SANDBOX_URL}
										autocomplete="off"
									/>
								</div>
							</div>
						</div>

						<div class="flex gap-2 w-full items-center justify-between">
							<div class="text-xs font-medium">
								{$i18n.t('Code Execution Timeout')}
							</div>

							<div class="">
								<Tooltip content={$i18n.t('Enter timeout in seconds')}>
									<input
										class="dark:bg-gray-900 w-fit rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-right"
										type="number"
										bind:value={config.CODE_EXECUTION_SANDBOX_TIMEOUT}
										placeholder={$i18n.t('e.g. 60')}
										autocomplete="off"
									/>
								</Tooltip>
							</div>
						</div>
					{/if}
				</div>

				<div class="mb-3.5">
					<div class=" mb-2.5 text-base font-medium">{$i18n.t('Code Interpreter')}</div>

					<hr class=" border-gray-100 dark:border-gray-850 my-2" />

					<div class="mb-2.5">
						<div class=" flex w-full justify-between">
							<div class=" self-center text-xs font-medium">
								{$i18n.t('Enable Code Interpreter')}
							</div>

							<Switch bind:state={config.ENABLE_CODE_INTERPRETER} />
						</div>
					</div>

					{#if config.ENABLE_CODE_INTERPRETER}
						<div class="mb-2.5">
							<div class="  flex w-full justify-between">
								<div class=" self-center text-xs font-medium">
									{$i18n.t('Code Interpreter Engine')}
								</div>
								<div class="flex items-center relative">
									<select
										class="dark:bg-gray-900 w-fit pr-8 rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-right"
										bind:value={config.CODE_INTERPRETER_ENGINE}
										placeholder={$i18n.t('Select a engine')}
										required
									>
										<option disabled selected value="">{$i18n.t('Select a engine')}</option>
										{#each engines as engine}
											<option value={engine}>{engine}</option>
										{/each}
									</select>
								</div>
							</div>

							{#if config.CODE_INTERPRETER_ENGINE === 'jupyter'}
								<div class="text-gray-500 text-xs">
									{$i18n.t(
										'Warning: Jupyter execution enables arbitrary code execution, posing severe security risks—proceed with extreme caution.'
									)}
								</div>
							{:else if config.CODE_INTERPRETER_ENGINE === 'sandbox'}
								<div class="text-gray-500 text-xs">
									{$i18n.t(
										'Sandbox executor provides isolated code execution with security restrictions.'
									)}
								</div>
							{/if}
						</div>

						{#if config.CODE_INTERPRETER_ENGINE === 'jupyter'}
							<div class="mb-2.5 flex flex-col gap-1.5 w-full">
								<div class="text-xs font-medium">
									{$i18n.t('Jupyter URL')}
								</div>

								<div class="flex w-full">
									<div class="flex-1">
										<input
											class="w-full text-sm py-0.5 placeholder:text-gray-300 dark:placeholder:text-gray-700 bg-transparent outline-hidden"
											type="text"
											placeholder={$i18n.t('Enter Jupyter URL')}
											bind:value={config.CODE_INTERPRETER_JUPYTER_URL}
											autocomplete="off"
										/>
									</div>
								</div>
							</div>

							<div class="mb-2.5 flex flex-col gap-1.5 w-full">
								<div class="flex gap-2 w-full items-center justify-between">
									<div class="text-xs font-medium">
										{$i18n.t('Jupyter Auth')}
									</div>

									<div>
										<select
											class="dark:bg-gray-900 w-fit pr-8 rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-left"
											bind:value={config.CODE_INTERPRETER_JUPYTER_AUTH}
											placeholder={$i18n.t('Select an auth method')}
										>
											<option selected value="">{$i18n.t('None')}</option>
											<option value="token">{$i18n.t('Token')}</option>
											<option value="password">{$i18n.t('Password')}</option>
										</select>
									</div>
								</div>

								{#if config.CODE_INTERPRETER_JUPYTER_AUTH}
									<div class="flex w-full gap-2">
										<div class="flex-1">
											{#if config.CODE_INTERPRETER_JUPYTER_AUTH === 'password'}
												<SensitiveInput
													type="text"
													placeholder={$i18n.t('Enter Jupyter Password')}
													bind:value={config.CODE_INTERPRETER_JUPYTER_AUTH_PASSWORD}
													autocomplete="off"
												/>
											{:else}
												<SensitiveInput
													type="text"
													placeholder={$i18n.t('Enter Jupyter Token')}
													bind:value={config.CODE_INTERPRETER_JUPYTER_AUTH_TOKEN}
													autocomplete="off"
												/>
											{/if}
										</div>
									</div>
								{/if}
							</div>

							<div class="flex gap-2 w-full items-center justify-between">
								<div class="text-xs font-medium">
									{$i18n.t('Code Execution Timeout')}
								</div>

								<div class="">
									<Tooltip content={$i18n.t('Enter timeout in seconds')}>
										<input
											class="dark:bg-gray-900 w-fit rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-right"
											type="number"
											bind:value={config.CODE_INTERPRETER_JUPYTER_TIMEOUT}
											placeholder={$i18n.t('e.g. 60')}
											autocomplete="off"
										/>
								</Tooltip>
							</div>
						</div>
					{:else if config.CODE_INTERPRETER_ENGINE === 'sandbox'}
						<div class="mb-2.5 flex flex-col gap-1.5 w-full">
							<div class="text-xs font-medium">
								{$i18n.t('Sandbox Executor URL')}
							</div>

							<div class="flex w-full">
								<div class="flex-1">
									<input
										class="w-full text-sm py-0.5 placeholder:text-gray-300 dark:placeholder:text-gray-700 bg-transparent outline-hidden"
										type="text"
										placeholder={$i18n.t('Enter Sandbox Executor URL (e.g. http://localhost:8090)')}
										bind:value={config.CODE_INTERPRETER_SANDBOX_URL}
										autocomplete="off"
									/>
								</div>
							</div>
						</div>

						<div class="flex gap-2 w-full items-center justify-between">
							<div class="text-xs font-medium">
								{$i18n.t('Code Execution Timeout')}
							</div>

							<div class="">
								<Tooltip content={$i18n.t('Enter timeout in seconds')}>
									<input
										class="dark:bg-gray-900 w-fit rounded-sm px-2 p-1 text-xs bg-transparent outline-hidden text-right"
										type="number"
										bind:value={config.CODE_INTERPRETER_SANDBOX_TIMEOUT}
										placeholder={$i18n.t('e.g. 60')}
										autocomplete="off"
									/>
								</Tooltip>
							</div>
						</div>
					{/if}

					<hr class="border-gray-100 dark:border-gray-850 my-2" />

						<div>
							<div class="py-0.5 w-full">
								<div class=" mb-2.5 text-xs font-medium">
									{$i18n.t('Code Interpreter Prompt Template')}
								</div>

								<Tooltip
									content={$i18n.t(
										'Leave empty to use the default prompt, or enter a custom prompt'
									)}
									placement="top-start"
								>
									<Textarea
										bind:value={config.CODE_INTERPRETER_PROMPT_TEMPLATE}
										placeholder={$i18n.t(
											'Leave empty to use the default prompt, or enter a custom prompt'
										)}
									/>
								</Tooltip>
							</div>
						</div>
					{/if}
				</div>
			</div>
		{/if}
	</div>
	<div class="flex justify-end pt-3 text-sm font-medium">
		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			type="submit"
		>
			{$i18n.t('Save')}
		</button>
	</div>
</form>

// src/components/admin/Settings/CodeExecution.tsx
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Separator } from '@/components/ui/separator';
import { Textarea } from '@/components/ui/textarea';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import SensitiveInput from '@/components/common/SensitiveInput';
import { getCodeExecutionConfig, setCodeExecutionConfig } from '@/lib/apis/configs';

interface CodeExecutionConfig {
  ENABLE_CODE_EXECUTION: boolean;
  CODE_EXECUTION_ENGINE: string;
  CODE_EXECUTION_JUPYTER_URL: string;
  CODE_EXECUTION_JUPYTER_AUTH: string;
  CODE_EXECUTION_JUPYTER_AUTH_PASSWORD: string;
  CODE_EXECUTION_JUPYTER_AUTH_TOKEN: string;
  CODE_EXECUTION_JUPYTER_TIMEOUT: number;
  CODE_EXECUTION_SANDBOX_URL: string;
  CODE_EXECUTION_SANDBOX_TIMEOUT: number;
  CODE_EXECUTION_SANDBOX_ENABLE_POOL: boolean;
  CODE_EXECUTION_SANDBOX_POOL_SIZE: number;
  CODE_EXECUTION_SANDBOX_POOL_MAX_REUSE: number;
  CODE_EXECUTION_SANDBOX_POOL_MAX_AGE: number;
  ENABLE_CODE_INTERPRETER: boolean;
  CODE_INTERPRETER_ENGINE: string;
  CODE_INTERPRETER_JUPYTER_URL: string;
  CODE_INTERPRETER_JUPYTER_AUTH: string;
  CODE_INTERPRETER_JUPYTER_AUTH_PASSWORD: string;
  CODE_INTERPRETER_JUPYTER_AUTH_TOKEN: string;
  CODE_INTERPRETER_JUPYTER_TIMEOUT: number;
  CODE_INTERPRETER_SANDBOX_URL: string;
  CODE_INTERPRETER_SANDBOX_TIMEOUT: number;
  CODE_INTERPRETER_PROMPT_TEMPLATE: string;
}

export default function CodeExecution() {
  const { t } = useTranslation();
  const [config, setConfig] = useState<CodeExecutionConfig | null>(null);
  const engines = ['jupyter', 'sandbox'];

  useEffect(() => {
    const init = async () => {
      const token = localStorage.getItem('token') || '';
      try {
        const res = await getCodeExecutionConfig(token);
        if (res) {
          setConfig(res);
        }
      } catch (error) {
        console.error('Failed to load code execution settings:', error);
        toast.error(t('Failed to load settings'));
      }
    };

    init();
  }, [t]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem('token') || '';

    try {
      if (config) {
        await setCodeExecutionConfig(token, config);
        toast.success(t('Settings saved successfully!'));
      }
    } catch (error) {
      console.error('Failed to update settings:', error);
      toast.error(t('Failed to update settings'));
    }
  };

  if (!config) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground">{t('Loading...')}</div>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-col h-full justify-between space-y-3 text-sm">
      <div className="space-y-3 overflow-y-scroll scrollbar-hidden h-full">
        {/* Code Execution Section */}
        <div>
          <div className="mb-3.5">
            <div className="mb-2.5 text-base font-medium">{t('General')}</div>
            <Separator />

            <div className="mb-2.5 mt-2">
              <div className="flex w-full justify-between items-center pr-2">
                <Label className="text-xs font-medium">{t('Enable Code Execution')}</Label>
                <Switch
                  checked={config.ENABLE_CODE_EXECUTION}
                  onCheckedChange={(checked) => setConfig({ ...config, ENABLE_CODE_EXECUTION: checked })}
                />
              </div>
            </div>

            <div className="mb-2.5">
              <div className="flex w-full justify-between items-center">
                <Label className="text-xs font-medium">{t('Code Execution Engine')}</Label>
                <Select
                  value={config.CODE_EXECUTION_ENGINE}
                  onValueChange={(value) => setConfig({ ...config, CODE_EXECUTION_ENGINE: value })}
                >
                  <SelectTrigger className="w-fit px-2 text-xs h-8">
                    <SelectValue placeholder={t('Select a engine')} />
                  </SelectTrigger>
                  <SelectContent>
                    {engines.map((engine) => (
                      <SelectItem key={engine} value={engine}>{engine}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {config.CODE_EXECUTION_ENGINE === 'jupyter' && (
                <div className="text-gray-500 text-xs mt-1">
                  {t('Warning: Jupyter execution enables arbitrary code execution, posing severe security risks—proceed with extreme caution.')}
                </div>
              )}
              {config.CODE_EXECUTION_ENGINE === 'sandbox' && (
                <div className="text-gray-500 text-xs mt-1">
                  {t('Sandbox executor provides isolated code execution with security restrictions.')}
                </div>
              )}
            </div>

            {/* Jupyter Configuration */}
            {config.CODE_EXECUTION_ENGINE === 'jupyter' && (
              <>
                <div className="mb-2.5">
                  <Label className="text-xs font-medium mb-2 block">{t('Jupyter URL')}</Label>
                  <Input
                    type="text"
                    placeholder={t('Enter Jupyter URL')}
                    value={config.CODE_EXECUTION_JUPYTER_URL}
                    onChange={(e) => setConfig({ ...config, CODE_EXECUTION_JUPYTER_URL: e.target.value })}
                    autoComplete="off"
                  />
                </div>

                <div className="mb-2.5">
                  <div className="flex gap-2 w-full items-center justify-between mb-2">
                    <Label className="text-xs font-medium">{t('Jupyter Auth')}</Label>
                    <Select
                      value={config.CODE_EXECUTION_JUPYTER_AUTH}
                      onValueChange={(value) => setConfig({ ...config, CODE_EXECUTION_JUPYTER_AUTH: value })}
                    >
                      <SelectTrigger className="w-fit px-2 text-xs h-8">
                        <SelectValue placeholder={t('None')} />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="">{t('None')}</SelectItem>
                        <SelectItem value="token">{t('Token')}</SelectItem>
                        <SelectItem value="password">{t('Password')}</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  {config.CODE_EXECUTION_JUPYTER_AUTH && (
                    <div className="flex w-full gap-2">
                      <div className="flex-1">
                        {config.CODE_EXECUTION_JUPYTER_AUTH === 'password' ? (
                          <SensitiveInput
                            type="text"
                            placeholder={t('Enter Jupyter Password')}
                            value={config.CODE_EXECUTION_JUPYTER_AUTH_PASSWORD}
                            onChange={(value) => setConfig({ ...config, CODE_EXECUTION_JUPYTER_AUTH_PASSWORD: value })}
                          />
                        ) : (
                          <SensitiveInput
                            type="text"
                            placeholder={t('Enter Jupyter Token')}
                            value={config.CODE_EXECUTION_JUPYTER_AUTH_TOKEN}
                            onChange={(value) => setConfig({ ...config, CODE_EXECUTION_JUPYTER_AUTH_TOKEN: value })}
                          />
                        )}
                      </div>
                    </div>
                  )}
                </div>

                <div className="flex gap-2 w-full items-center justify-between">
                  <Label className="text-xs font-medium">{t('Code Execution Timeout')}</Label>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Input
                        type="number"
                        className="w-fit px-2 text-xs h-8"
                        placeholder={t('e.g. 60')}
                        value={config.CODE_EXECUTION_JUPYTER_TIMEOUT}
                        onChange={(e) => setConfig({ ...config, CODE_EXECUTION_JUPYTER_TIMEOUT: parseInt(e.target.value) })}
                        autoComplete="off"
                      />
                    </TooltipTrigger>
                    <TooltipContent>{t('Enter timeout in seconds')}</TooltipContent>
                  </Tooltip>
                </div>
              </>
            )}

            {/* Sandbox Configuration */}
            {config.CODE_EXECUTION_ENGINE === 'sandbox' && (
              <>
                <div className="mb-2.5">
                  <Label className="text-xs font-medium mb-2 block">{t('Sandbox Executor URL')}</Label>
                  <Input
                    type="text"
                    placeholder={t('Enter Sandbox Executor URL (e.g. http://localhost:8090)')}
                    value={config.CODE_EXECUTION_SANDBOX_URL}
                    onChange={(e) => setConfig({ ...config, CODE_EXECUTION_SANDBOX_URL: e.target.value })}
                    autoComplete="off"
                  />
                </div>

                <div className="flex gap-2 w-full items-center justify-between mb-2.5">
                  <Label className="text-xs font-medium">{t('Code Execution Timeout')}</Label>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Input
                        type="number"
                        className="w-fit px-2 text-xs h-8"
                        placeholder={t('e.g. 60')}
                        value={config.CODE_EXECUTION_SANDBOX_TIMEOUT}
                        onChange={(e) => setConfig({ ...config, CODE_EXECUTION_SANDBOX_TIMEOUT: parseInt(e.target.value) })}
                        autoComplete="off"
                      />
                    </TooltipTrigger>
                    <TooltipContent>{t('Enter timeout in seconds')}</TooltipContent>
                  </Tooltip>
                </div>

                <Separator className="my-2" />

                <div className="mb-2.5 text-xs font-medium">{t('Container Pool Settings')}</div>

                <div className="mb-2.5">
                  <div className="flex w-full justify-between items-center pr-2">
                    <Label className="text-xs font-medium">{t('Enable Container Pool')}</Label>
                    <Switch
                      checked={config.CODE_EXECUTION_SANDBOX_ENABLE_POOL}
                      onCheckedChange={(checked) => setConfig({ ...config, CODE_EXECUTION_SANDBOX_ENABLE_POOL: checked })}
                    />
                  </div>
                  <div className="text-gray-500 text-xs mt-1">
                    {t('Reuse containers for faster execution (recommended)')}
                  </div>
                </div>

                {config.CODE_EXECUTION_SANDBOX_ENABLE_POOL && (
                  <>
                    <div className="flex gap-2 w-full items-center justify-between mb-2.5">
                      <Label className="text-xs font-medium">{t('Pool Size Per Language')}</Label>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Input
                            type="number"
                            className="w-fit px-2 text-xs h-8"
                            placeholder={t('e.g. 3')}
                            min={1}
                            max={10}
                            value={config.CODE_EXECUTION_SANDBOX_POOL_SIZE}
                            onChange={(e) => setConfig({ ...config, CODE_EXECUTION_SANDBOX_POOL_SIZE: parseInt(e.target.value) })}
                            autoComplete="off"
                          />
                        </TooltipTrigger>
                        <TooltipContent>{t('Number of warm containers per language')}</TooltipContent>
                      </Tooltip>
                    </div>

                    <div className="flex gap-2 w-full items-center justify-between mb-2.5">
                      <Label className="text-xs font-medium">{t('Max Container Reuse')}</Label>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Input
                            type="number"
                            className="w-fit px-2 text-xs h-8"
                            placeholder={t('e.g. 50')}
                            min={5}
                            max={200}
                            value={config.CODE_EXECUTION_SANDBOX_POOL_MAX_REUSE}
                            onChange={(e) => setConfig({ ...config, CODE_EXECUTION_SANDBOX_POOL_MAX_REUSE: parseInt(e.target.value) })}
                            autoComplete="off"
                          />
                        </TooltipTrigger>
                        <TooltipContent>{t('Recreate container after N executions')}</TooltipContent>
                      </Tooltip>
                    </div>

                    <div className="flex gap-2 w-full items-center justify-between">
                      <Label className="text-xs font-medium">{t('Max Container Age (seconds)')}</Label>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Input
                            type="number"
                            className="w-fit px-2 text-xs h-8"
                            placeholder={t('e.g. 600')}
                            min={60}
                            max={3600}
                            value={config.CODE_EXECUTION_SANDBOX_POOL_MAX_AGE}
                            onChange={(e) => setConfig({ ...config, CODE_EXECUTION_SANDBOX_POOL_MAX_AGE: parseInt(e.target.value) })}
                            autoComplete="off"
                          />
                        </TooltipTrigger>
                        <TooltipContent>{t('Recreate container after N seconds')}</TooltipContent>
                      </Tooltip>
                    </div>
                  </>
                )}
              </>
            )}
          </div>

          {/* Code Interpreter Section */}
          <div className="mb-3.5">
            <div className="mb-2.5 text-base font-medium">{t('Code Interpreter')}</div>
            <Separator />

            <div className="mb-2.5 mt-2">
              <div className="flex w-full justify-between items-center pr-2">
                <Label className="text-xs font-medium">{t('Enable Code Interpreter')}</Label>
                <Switch
                  checked={config.ENABLE_CODE_INTERPRETER}
                  onCheckedChange={(checked) => setConfig({ ...config, ENABLE_CODE_INTERPRETER: checked })}
                />
              </div>
            </div>

            {config.ENABLE_CODE_INTERPRETER && (
              <>
                <div className="mb-2.5">
                  <div className="flex w-full justify-between items-center">
                    <Label className="text-xs font-medium">{t('Code Interpreter Engine')}</Label>
                    <Select
                      value={config.CODE_INTERPRETER_ENGINE}
                      onValueChange={(value) => setConfig({ ...config, CODE_INTERPRETER_ENGINE: value })}
                    >
                      <SelectTrigger className="w-fit px-2 text-xs h-8">
                        <SelectValue placeholder={t('Select a engine')} />
                      </SelectTrigger>
                      <SelectContent>
                        {engines.map((engine) => (
                          <SelectItem key={engine} value={engine}>{engine}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  {config.CODE_INTERPRETER_ENGINE === 'jupyter' && (
                    <div className="text-gray-500 text-xs mt-1">
                      {t('Warning: Jupyter execution enables arbitrary code execution, posing severe security risks—proceed with extreme caution.')}
                    </div>
                  )}
                  {config.CODE_INTERPRETER_ENGINE === 'sandbox' && (
                    <div className="text-gray-500 text-xs mt-1">
                      {t('Sandbox executor provides isolated code execution with security restrictions.')}
                    </div>
                  )}
                </div>

                {/* Code Interpreter Jupyter Configuration */}
                {config.CODE_INTERPRETER_ENGINE === 'jupyter' && (
                  <>
                    <div className="mb-2.5">
                      <Label className="text-xs font-medium mb-2 block">{t('Jupyter URL')}</Label>
                      <Input
                        type="text"
                        placeholder={t('Enter Jupyter URL')}
                        value={config.CODE_INTERPRETER_JUPYTER_URL}
                        onChange={(e) => setConfig({ ...config, CODE_INTERPRETER_JUPYTER_URL: e.target.value })}
                        autoComplete="off"
                      />
                    </div>

                    <div className="mb-2.5">
                      <div className="flex gap-2 w-full items-center justify-between mb-2">
                        <Label className="text-xs font-medium">{t('Jupyter Auth')}</Label>
                        <Select
                          value={config.CODE_INTERPRETER_JUPYTER_AUTH}
                          onValueChange={(value) => setConfig({ ...config, CODE_INTERPRETER_JUPYTER_AUTH: value })}
                        >
                          <SelectTrigger className="w-fit px-2 text-xs h-8">
                            <SelectValue placeholder={t('None')} />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="">{t('None')}</SelectItem>
                            <SelectItem value="token">{t('Token')}</SelectItem>
                            <SelectItem value="password">{t('Password')}</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>

                      {config.CODE_INTERPRETER_JUPYTER_AUTH && (
                        <div className="flex w-full gap-2">
                          <div className="flex-1">
                            {config.CODE_INTERPRETER_JUPYTER_AUTH === 'password' ? (
                              <SensitiveInput
                                type="text"
                                placeholder={t('Enter Jupyter Password')}
                                value={config.CODE_INTERPRETER_JUPYTER_AUTH_PASSWORD}
                                onChange={(value) => setConfig({ ...config, CODE_INTERPRETER_JUPYTER_AUTH_PASSWORD: value })}
                              />
                            ) : (
                              <SensitiveInput
                                type="text"
                                placeholder={t('Enter Jupyter Token')}
                                value={config.CODE_INTERPRETER_JUPYTER_AUTH_TOKEN}
                                onChange={(value) => setConfig({ ...config, CODE_INTERPRETER_JUPYTER_AUTH_TOKEN: value })}
                              />
                            )}
                          </div>
                        </div>
                      )}
                    </div>

                    <div className="flex gap-2 w-full items-center justify-between">
                      <Label className="text-xs font-medium">{t('Code Execution Timeout')}</Label>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Input
                            type="number"
                            className="w-fit px-2 text-xs h-8"
                            placeholder={t('e.g. 60')}
                            value={config.CODE_INTERPRETER_JUPYTER_TIMEOUT}
                            onChange={(e) => setConfig({ ...config, CODE_INTERPRETER_JUPYTER_TIMEOUT: parseInt(e.target.value) })}
                            autoComplete="off"
                          />
                        </TooltipTrigger>
                        <TooltipContent>{t('Enter timeout in seconds')}</TooltipContent>
                      </Tooltip>
                    </div>
                  </>
                )}

                {/* Code Interpreter Sandbox Configuration */}
                {config.CODE_INTERPRETER_ENGINE === 'sandbox' && (
                  <>
                    <div className="mb-2.5">
                      <Label className="text-xs font-medium mb-2 block">{t('Sandbox Executor URL')}</Label>
                      <Input
                        type="text"
                        placeholder={t('Enter Sandbox Executor URL (e.g. http://localhost:8090)')}
                        value={config.CODE_INTERPRETER_SANDBOX_URL}
                        onChange={(e) => setConfig({ ...config, CODE_INTERPRETER_SANDBOX_URL: e.target.value })}
                        autoComplete="off"
                      />
                    </div>

                    <div className="flex gap-2 w-full items-center justify-between">
                      <Label className="text-xs font-medium">{t('Code Execution Timeout')}</Label>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Input
                            type="number"
                            className="w-fit px-2 text-xs h-8"
                            placeholder={t('e.g. 60')}
                            value={config.CODE_INTERPRETER_SANDBOX_TIMEOUT}
                            onChange={(e) => setConfig({ ...config, CODE_INTERPRETER_SANDBOX_TIMEOUT: parseInt(e.target.value) })}
                            autoComplete="off"
                          />
                        </TooltipTrigger>
                        <TooltipContent>{t('Enter timeout in seconds')}</TooltipContent>
                      </Tooltip>
                    </div>
                  </>
                )}

                <Separator className="my-2" />

                <div>
                  <div className="py-0.5 w-full">
                    <Label className="text-xs font-medium mb-2 block">{t('Code Interpreter Prompt Template')}</Label>
                    <Tooltip>
                      <TooltipTrigger asChild className="w-full">
                        <Textarea
                          value={config.CODE_INTERPRETER_PROMPT_TEMPLATE}
                          onChange={(e) => setConfig({ ...config, CODE_INTERPRETER_PROMPT_TEMPLATE: e.target.value })}
                          placeholder={t('Leave empty to use the default prompt, or enter a custom prompt')}
                          className="min-h-[80px]"
                        />
                      </TooltipTrigger>
                      <TooltipContent>{t('Leave empty to use the default prompt, or enter a custom prompt')}</TooltipContent>
                    </Tooltip>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      <div className="flex justify-end pt-3 text-sm font-medium">
        <Button type="submit" className="px-3.5 py-1.5 rounded-full">
          {t('Save')}
        </Button>
      </div>
    </form>
  );
}
