// src/lib/components/admin/Settings/General.svelte
<script lang="ts">
	import DOMPurify from 'dompurify';

	import { getVersionUpdates, getWebhookUrl, updateWebhookUrl } from '$lib/apis';
	import {
		getAdminConfig,
		getLdapConfig,
		getLdapServer,
		updateAdminConfig,
		updateLdapConfig,
		updateLdapServer
	} from '$lib/apis/auths';
	import SensitiveInput from '$lib/components/common/SensitiveInput.svelte';
	import Switch from '$lib/components/common/Switch.svelte';
	import Tooltip from '$lib/components/common/Tooltip.svelte';
	import { WEBUI_BUILD_HASH, WEBUI_VERSION } from '$lib/constants';
	import { config } from '$lib/stores';
	import { compareVersion } from '$lib/utils';
	import { onMount, getContext } from 'svelte';
	import { toast } from 'svelte-sonner';
	import Textarea from '$lib/components/common/Textarea.svelte';

	const i18n = getContext('i18n');

	export let saveHandler: Function;

	let updateAvailable = null;
	let version = {
		current: '',
		latest: ''
	};

	let adminConfig = null;
	let webhookUrl = '';

	// LDAP
	let ENABLE_LDAP = false;
	let LDAP_SERVER = {
		label: '',
		host: '',
		port: '',
		attribute_for_mail: 'mail',
		attribute_for_username: 'uid',
		app_dn: '',
		app_dn_password: '',
		search_base: '',
		search_filters: '',
		use_tls: false,
		certificate_path: '',
		ciphers: ''
	};

	const checkForVersionUpdates = async () => {
		updateAvailable = null;
		version = await getVersionUpdates(localStorage.token).catch((error) => {
			return {
				current: WEBUI_VERSION,
				latest: WEBUI_VERSION
			};
		});

		console.info(version);

		updateAvailable = compareVersion(version.latest, version.current);
		console.info(updateAvailable);
	};

	const updateLdapServerHandler = async () => {
		if (!ENABLE_LDAP) return;
		const res = await updateLdapServer(localStorage.token, LDAP_SERVER).catch((error) => {
			toast.error(`${error}`);
			return null;
		});
		if (res) {
			toast.success($i18n.t('LDAP server updated'));
		}
	};

	const updateHandler = async () => {
		webhookUrl = await updateWebhookUrl(localStorage.token, webhookUrl);
		const res = await updateAdminConfig(localStorage.token, adminConfig);
		await updateLdapConfig(localStorage.token, ENABLE_LDAP);
		await updateLdapServerHandler();

		if (res) {
			saveHandler();
		} else {
			toast.error($i18n.t('Failed to update settings'));
		}
	};

	onMount(async () => {
		if ($config?.features?.enable_version_update_check) {
			checkForVersionUpdates();
		}

		await Promise.all([
			(async () => {
				adminConfig = await getAdminConfig(localStorage.token);
			})(),

			(async () => {
				webhookUrl = await getWebhookUrl(localStorage.token);
			})(),
			(async () => {
				LDAP_SERVER = await getLdapServer(localStorage.token);
			})()
		]);

		const ldapConfig = await getLdapConfig(localStorage.token);
		ENABLE_LDAP = ldapConfig.ENABLE_LDAP;
	});
</script>

<form
	class="flex flex-col h-full justify-between space-y-3 text-sm"
	on:submit|preventDefault={async () => {
		updateHandler();
	}}
>
	<div class="mt-0.5 space-y-3 overflow-y-scroll scrollbar-hidden h-full">
		{#if adminConfig !== null}
			<div class="">
				<div class="mb-3.5">
					<div class=" mb-2.5 text-base font-medium">{$i18n.t('General')}</div>

					<hr class=" border-gray-100 dark:border-gray-850 my-2" />

					<div class="mb-2.5">
						<div class=" mb-1 text-xs font-medium flex space-x-2 items-center">
							<div>
								{$i18n.t('Version')}
							</div>
						</div>
						<div class="flex w-full justify-between items-center">
							<div class="flex flex-col text-xs text-gray-700 dark:text-gray-200">
								<div class="flex gap-1">
									<Tooltip content={WEBUI_BUILD_HASH}>
										v{WEBUI_VERSION}
									</Tooltip>

									{#if $config?.features?.enable_version_update_check}
										<a
											href="https://github.com/knoxchat/open-webui-rust/releases/tag/v{version.latest}"
											target="_blank"
										>
											{updateAvailable === null
												? $i18n.t('Checking for updates...')
												: updateAvailable
													? `(v${version.latest} ${$i18n.t('available!')})`
													: $i18n.t('(latest)')}
										</a>
									{/if}
							</div>
						</div>

							{#if $config?.features?.enable_version_update_check}
								<button
									class=" text-xs px-3 py-1.5 bg-gray-50 hover:bg-gray-100 dark:bg-gray-850 dark:hover:bg-gray-800 transition rounded-lg font-medium"
									type="button"
									on:click={() => {
										checkForVersionUpdates();
									}}
								>
									{$i18n.t('Check for updates')}
								</button>
							{/if}
						</div>
					</div>

					<div class="mb-2.5">
						<div class="flex w-full justify-between items-center">
							<div class="text-xs pr-2">
								<div class="">
									{$i18n.t('License')}
								</div>

								{#if $config?.license_metadata}
									<a
										href="https://docs.openwebui.com/enterprise"
										target="_blank"
										class="text-gray-500 mt-0.5"
									>
										<span class=" capitalize text-black dark:text-white"
											>{$config?.license_metadata?.type}
											license</span
										>
										registered to
										<span class=" capitalize text-black dark:text-white"
											>{$config?.license_metadata?.organization_name}</span
										>
										for
										<span class=" font-medium text-black dark:text-white"
											>{$config?.license_metadata?.seats ?? 'Unlimited'} users.</span
										>
									</a>
									{#if $config?.license_metadata?.html}
										<div class="mt-0.5">
											{@html DOMPurify.sanitize($config?.license_metadata?.html)}
										</div>
									{/if}
								{:else}
									<a
										class=" text-xs hover:underline"
										href="https://docs.openwebui.com/enterprise"
										target="_blank"
									>
										<span class="text-gray-500">
											{$i18n.t(
												'Upgrade to a licensed plan for enhanced capabilities, including custom theming and branding, and dedicated support.'
											)}
										</span>
									</a>
								{/if}
							</div>

							<!-- <button
								class="flex-shrink-0 text-xs px-3 py-1.5 bg-gray-50 hover:bg-gray-100 dark:bg-gray-850 dark:hover:bg-gray-800 transition rounded-lg font-medium"
							>
								{$i18n.t('Activate')}
							</button> -->
						</div>
					</div>
				</div>

				<div class="mb-3">
					<div class=" mb-2.5 text-base font-medium">{$i18n.t('Authentication')}</div>

					<hr class=" border-gray-100 dark:border-gray-850 my-2" />

					<div class="  mb-2.5 flex w-full justify-between">
						<div class=" self-center text-xs font-medium">{$i18n.t('Default User Role')}</div>
						<div class="flex items-center relative">
							<select
								class="dark:bg-gray-900 w-fit pr-8 rounded-sm px-2 text-xs bg-transparent outline-hidden text-right"
								bind:value={adminConfig.DEFAULT_USER_ROLE}
								placeholder={$i18n.t('Select a role')}
							>
								<option value="pending">{$i18n.t('pending')}</option>
								<option value="user">{$i18n.t('user')}</option>
								<option value="admin">{$i18n.t('admin')}</option>
							</select>
						</div>
					</div>

					<div class=" mb-2.5 flex w-full justify-between pr-2">
						<div class=" self-center text-xs font-medium">{$i18n.t('Enable New Sign Ups')}</div>

						<Switch bind:state={adminConfig.ENABLE_SIGNUP} />
					</div>

					<div class="mb-2.5 flex w-full items-center justify-between pr-2">
						<div class=" self-center text-xs font-medium">
							{$i18n.t('Show Admin Details in Account Pending Overlay')}
						</div>

						<Switch bind:state={adminConfig.SHOW_ADMIN_DETAILS} />
					</div>

					<div class="mb-2.5">
						<div class=" self-center text-xs font-medium mb-2">
							{$i18n.t('Pending User Overlay Title')}
						</div>
						<Textarea
							placeholder={$i18n.t(
								'Enter a title for the pending user info overlay. Leave empty for default.'
							)}
							bind:value={adminConfig.PENDING_USER_OVERLAY_TITLE}
						/>
					</div>

					<div class="mb-2.5">
						<div class=" self-center text-xs font-medium mb-2">
							{$i18n.t('Pending User Overlay Content')}
						</div>
						<Textarea
							placeholder={$i18n.t(
								'Enter content for the pending user info overlay. Leave empty for default.'
							)}
							bind:value={adminConfig.PENDING_USER_OVERLAY_CONTENT}
						/>
					</div>

					<div class="mb-2.5 flex w-full justify-between pr-2">
						<div class=" self-center text-xs font-medium">{$i18n.t('Enable API Key')}</div>

						<Switch bind:state={adminConfig.ENABLE_API_KEY} />
					</div>

					{#if adminConfig?.ENABLE_API_KEY}
						<div class="mb-2.5 flex w-full justify-between pr-2">
							<div class=" self-center text-xs font-medium">
								{$i18n.t('API Key Endpoint Restrictions')}
							</div>

							<Switch bind:state={adminConfig.ENABLE_API_KEY_ENDPOINT_RESTRICTIONS} />
						</div>

						{#if adminConfig?.ENABLE_API_KEY_ENDPOINT_RESTRICTIONS}
							<div class=" flex w-full flex-col pr-2">
								<div class=" text-xs font-medium">
									{$i18n.t('Allowed Endpoints')}
								</div>

								<input
									class="w-full mt-1 rounded-lg text-sm dark:text-gray-300 bg-transparent outline-hidden"
									type="text"
									placeholder={`e.g.) /api/v1/messages, /api/v1/channels`}
									bind:value={adminConfig.API_KEY_ALLOWED_ENDPOINTS}
								/>

								<div class="mt-2 text-xs text-gray-400 dark:text-gray-500">
									<!-- https://docs.openwebui.com/getting-started/advanced-topics/api-endpoints -->
									<a
										href="https://docs.openwebui.com/getting-started/api-endpoints"
										target="_blank"
										class=" text-gray-300 font-medium underline"
									>
										{$i18n.t('To learn more about available endpoints, visit our documentation.')}
									</a>
								</div>
							</div>
						{/if}
					{/if}

					<div class=" mb-2.5 w-full justify-between">
						<div class="flex w-full justify-between">
							<div class=" self-center text-xs font-medium">{$i18n.t('JWT Expiration')}</div>
						</div>

						<div class="flex mt-2 space-x-2">
							<input
								class="w-full rounded-lg py-2 px-4 text-sm bg-gray-50 dark:text-gray-300 dark:bg-gray-850 outline-hidden"
								type="text"
								placeholder={`e.g.) "30m","1h", "10d". `}
								bind:value={adminConfig.JWT_EXPIRES_IN}
							/>
						</div>

						<div class="mt-2 text-xs text-gray-400 dark:text-gray-500">
							{$i18n.t('Valid time units:')}
							<span class=" text-gray-300 font-medium"
								>{$i18n.t("'s', 'm', 'h', 'd', 'w' or '-1' for no expiration.")}</span
							>
						</div>
					</div>

					<div class=" space-y-3">
						<div class="mt-2 space-y-2 pr-1.5">
							<div class="flex justify-between items-center text-sm">
								<div class="  font-medium">{$i18n.t('LDAP')}</div>

								<div class="mt-1">
									<Switch bind:state={ENABLE_LDAP} />
								</div>
							</div>

							{#if ENABLE_LDAP}
								<div class="flex flex-col gap-1">
									<div class="flex w-full gap-2">
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Label')}
											</div>
											<input
												class="w-full bg-transparent outline-hidden py-0.5"
												required
												placeholder={$i18n.t('Enter server label')}
												bind:value={LDAP_SERVER.label}
											/>
										</div>
										<div class="w-full"></div>
									</div>
									<div class="flex w-full gap-2">
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Host')}
											</div>
											<input
												class="w-full bg-transparent outline-hidden py-0.5"
												required
												placeholder={$i18n.t('Enter server host')}
												bind:value={LDAP_SERVER.host}
											/>
										</div>
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Port')}
											</div>
											<Tooltip
												placement="top-start"
												content={$i18n.t('Default to 389 or 636 if TLS is enabled')}
												className="w-full"
											>
												<input
													class="w-full bg-transparent outline-hidden py-0.5"
													type="number"
													placeholder={$i18n.t('Enter server port')}
													bind:value={LDAP_SERVER.port}
												/>
											</Tooltip>
										</div>
									</div>
									<div class="flex w-full gap-2">
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Application DN')}
											</div>
											<Tooltip
												content={$i18n.t('The Application Account DN you bind with for search')}
												placement="top-start"
											>
												<input
													class="w-full bg-transparent outline-hidden py-0.5"
													required
													placeholder={$i18n.t('Enter Application DN')}
													bind:value={LDAP_SERVER.app_dn}
												/>
											</Tooltip>
										</div>
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Application DN Password')}
											</div>
											<SensitiveInput
												placeholder={$i18n.t('Enter Application DN Password')}
												bind:value={LDAP_SERVER.app_dn_password}
											/>
										</div>
									</div>
									<div class="flex w-full gap-2">
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Attribute for Mail')}
											</div>
											<Tooltip
												content={$i18n.t(
													'The LDAP attribute that maps to the mail that users use to sign in.'
												)}
												placement="top-start"
											>
												<input
													class="w-full bg-transparent outline-hidden py-0.5"
													required
													placeholder={$i18n.t('Example: mail')}
													bind:value={LDAP_SERVER.attribute_for_mail}
												/>
											</Tooltip>
										</div>
									</div>
									<div class="flex w-full gap-2">
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Attribute for Username')}
											</div>
											<Tooltip
												content={$i18n.t(
													'The LDAP attribute that maps to the username that users use to sign in.'
												)}
												placement="top-start"
											>
												<input
													class="w-full bg-transparent outline-hidden py-0.5"
													required
													placeholder={$i18n.t(
														'Example: sAMAccountName or uid or userPrincipalName'
													)}
													bind:value={LDAP_SERVER.attribute_for_username}
												/>
											</Tooltip>
										</div>
									</div>
									<div class="flex w-full gap-2">
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Search Base')}
											</div>
											<Tooltip
												content={$i18n.t('The base to search for users')}
												placement="top-start"
											>
												<input
													class="w-full bg-transparent outline-hidden py-0.5"
													required
													placeholder={$i18n.t('Example: ou=users,dc=foo,dc=example')}
													bind:value={LDAP_SERVER.search_base}
												/>
											</Tooltip>
										</div>
									</div>
									<div class="flex w-full gap-2">
										<div class="w-full">
											<div class=" self-center text-xs font-medium min-w-fit mb-1">
												{$i18n.t('Search Filters')}
											</div>
											<input
												class="w-full bg-transparent outline-hidden py-0.5"
												placeholder={$i18n.t('Example: (&(objectClass=inetOrgPerson)(uid=%s))')}
												bind:value={LDAP_SERVER.search_filters}
											/>
										</div>
									</div>
									<div class="text-xs text-gray-400 dark:text-gray-500">
										<a
											class=" text-gray-300 font-medium underline"
											href="https://ldap.com/ldap-filters/"
											target="_blank"
										>
											{$i18n.t('Click here for filter guides.')}
										</a>
									</div>
									<div>
										<div class="flex justify-between items-center text-sm">
											<div class="  font-medium">{$i18n.t('TLS')}</div>

											<div class="mt-1">
												<Switch bind:state={LDAP_SERVER.use_tls} />
											</div>
										</div>
										{#if LDAP_SERVER.use_tls}
											<div class="flex w-full gap-2">
												<div class="w-full">
													<div class=" self-center text-xs font-medium min-w-fit mb-1 mt-1">
														{$i18n.t('Certificate Path')}
													</div>
													<input
														class="w-full bg-transparent outline-hidden py-0.5"
														placeholder={$i18n.t('Enter certificate path')}
														bind:value={LDAP_SERVER.certificate_path}
													/>
												</div>
											</div>
											<div class="flex justify-between items-center text-xs">
												<div class=" font-medium">{$i18n.t('Validate certificate')}</div>

												<div class="mt-1">
													<Switch bind:state={LDAP_SERVER.validate_cert} />
												</div>
											</div>
											<div class="flex w-full gap-2">
												<div class="w-full">
													<div class=" self-center text-xs font-medium min-w-fit mb-1">
														{$i18n.t('Ciphers')}
													</div>
													<Tooltip content={$i18n.t('Default to ALL')} placement="top-start">
														<input
															class="w-full bg-transparent outline-hidden py-0.5"
															placeholder={$i18n.t('Example: ALL')}
															bind:value={LDAP_SERVER.ciphers}
														/>
													</Tooltip>
												</div>
												<div class="w-full"></div>
											</div>
										{/if}
									</div>
								</div>
							{/if}
						</div>
					</div>
				</div>

				<div class="mb-3">
					<div class=" mb-2.5 text-base font-medium">{$i18n.t('Features')}</div>

					<hr class=" border-gray-100 dark:border-gray-850 my-2" />

					<div class="mb-2.5 flex w-full items-center justify-between pr-2">
						<div class=" self-center text-xs font-medium">
							{$i18n.t('Enable Community Sharing')}
						</div>

						<Switch bind:state={adminConfig.ENABLE_COMMUNITY_SHARING} />
					</div>

					<div class="mb-2.5 flex w-full items-center justify-between pr-2">
						<div class=" self-center text-xs font-medium">{$i18n.t('Enable Message Rating')}</div>

						<Switch bind:state={adminConfig.ENABLE_MESSAGE_RATING} />
					</div>

					<div class="mb-2.5 flex w-full items-center justify-between pr-2">
						<div class=" self-center text-xs font-medium">
							{$i18n.t('Notes')} ({$i18n.t('Beta')})
						</div>

						<Switch bind:state={adminConfig.ENABLE_NOTES} />
					</div>

					<div class="mb-2.5 flex w-full items-center justify-between pr-2">
						<div class=" self-center text-xs font-medium">
							{$i18n.t('Channels')} ({$i18n.t('Beta')})
						</div>

						<Switch bind:state={adminConfig.ENABLE_CHANNELS} />
					</div>

					<div class="mb-2.5 flex w-full items-center justify-between pr-2">
						<div class=" self-center text-xs font-medium">
							{$i18n.t('User Webhooks')}
						</div>

						<Switch bind:state={adminConfig.ENABLE_USER_WEBHOOKS} />
					</div>

					<div class="mb-2.5">
						<div class=" self-center text-xs font-medium mb-2">
							{$i18n.t('Response Watermark')}
						</div>
						<Textarea
							placeholder={$i18n.t('Enter a watermark for the response. Leave empty for none.')}
							bind:value={adminConfig.RESPONSE_WATERMARK}
						/>
					</div>

					<div class="mb-2.5 w-full justify-between">
						<div class="flex w-full justify-between">
							<div class=" self-center text-xs font-medium">{$i18n.t('WebUI URL')}</div>
						</div>

						<div class="flex mt-2 space-x-2">
							<input
								class="w-full rounded-lg py-2 px-4 text-sm bg-gray-50 dark:text-gray-300 dark:bg-gray-850 outline-hidden"
								type="text"
								placeholder={`e.g.) "http://localhost:3000"`}
								bind:value={adminConfig.WEBUI_URL}
							/>
						</div>

						<div class="mt-2 text-xs text-gray-400 dark:text-gray-500">
							{$i18n.t(
								'Enter the public URL of your WebUI. This URL will be used to generate links in the notifications.'
							)}
						</div>
					</div>

					<div class=" w-full justify-between">
						<div class="flex w-full justify-between">
							<div class=" self-center text-xs font-medium">{$i18n.t('Webhook URL')}</div>
						</div>

						<div class="flex mt-2 space-x-2">
							<input
								class="w-full rounded-lg py-2 px-4 text-sm bg-gray-50 dark:text-gray-300 dark:bg-gray-850 outline-hidden"
								type="text"
								placeholder={`https://example.com/webhook`}
								bind:value={webhookUrl}
							/>
						</div>
					</div>
				</div>
			</div>
		{/if}
	</div>

	<div class="flex justify-end pt-3 text-sm font-medium">
		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			type="submit"
		>
			{$i18n.t('Save')}
		</button>
	</div>
</form>

// src/components/admin/Settings/General.tsx
import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Separator } from '@/components/ui/separator';
import { Textarea } from '@/components/ui/textarea';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import SensitiveInput from '@/components/common/SensitiveInput';
import {
  getAdminConfig,
  updateAdminConfig,
  getLdapConfig,
  updateLdapConfig,
  getLdapServer,
  updateLdapServer
} from '@/lib/apis/auths';
import { getWebhookUrl, updateWebhookUrl, getVersionUpdates, getBackendConfig } from '@/lib/apis';
import { WEBUI_VERSION } from '@/lib/constants';

interface AdminConfig {
  DEFAULT_USER_ROLE: string;
  ENABLE_SIGNUP: boolean;
  SHOW_ADMIN_DETAILS: boolean;
  PENDING_USER_OVERLAY_TITLE: string;
  PENDING_USER_OVERLAY_CONTENT: string;
  ENABLE_API_KEY: boolean;
  ENABLE_API_KEY_ENDPOINT_RESTRICTIONS: boolean;
  API_KEY_ALLOWED_ENDPOINTS: string;
  JWT_EXPIRES_IN: string;
  ENABLE_COMMUNITY_SHARING: boolean;
  ENABLE_MESSAGE_RATING: boolean;
  ENABLE_NOTES: boolean;
  ENABLE_CHANNELS: boolean;
  ENABLE_USER_WEBHOOKS: boolean;
  RESPONSE_WATERMARK: string;
  WEBUI_URL: string;
}

interface LdapServer {
  label: string;
  host: string;
  port: string;
  attribute_for_mail: string;
  attribute_for_username: string;
  app_dn: string;
  app_dn_password: string;
  search_base: string;
  search_filters: string;
  use_tls: boolean;
  certificate_path: string;
  ciphers: string;
  validate_cert?: boolean;
}

export default function General() {
  const { t } = useTranslation();
  const [adminConfig, setAdminConfig] = useState<AdminConfig | null>(null);
  const [webhookUrl, setWebhookUrl] = useState('');
  const [enableLdap, setEnableLdap] = useState(false);
  const [ldapServer, setLdapServer] = useState<LdapServer>({
    label: '',
    host: '',
    port: '',
    attribute_for_mail: 'mail',
    attribute_for_username: 'uid',
    app_dn: '',
    app_dn_password: '',
    search_base: '',
    search_filters: '',
    use_tls: false,
    certificate_path: '',
    ciphers: '',
    validate_cert: false
  });

  const [updateAvailable, setUpdateAvailable] = useState<boolean | null>(null);
  const [version, setVersion] = useState({ current: '', latest: '' });

  useEffect(() => {
    const init = async () => {
      const token = localStorage.getItem('token') || '';
      
      try {
        const [config, webhook, ldapCfg, ldapSrv, backendConfig] = await Promise.all([
          getAdminConfig(token),
          getWebhookUrl(token),
          getLdapConfig(token),
          getLdapServer(token),
          getBackendConfig()
        ]);

        if (config) setAdminConfig(config);
        if (webhook) setWebhookUrl(webhook);
        if (ldapCfg) setEnableLdap(ldapCfg.ENABLE_LDAP);
        if (ldapSrv) setLdapServer(ldapSrv);

        // Check for version updates if enabled
        if (backendConfig?.features?.enable_version_update_check) {
          try {
            const versionData = await getVersionUpdates(token);
            if (versionData) {
              setVersion(versionData);
              const current = versionData.current || WEBUI_VERSION;
              const latest = versionData.latest || WEBUI_VERSION;
              setUpdateAvailable(compareVersion(latest, current));
            }
          } catch (error) {
            console.error('Failed to check for updates:', error);
          }
        }
      } catch (error) {
        console.error('Failed to load settings:', error);
        toast.error(t('Failed to load settings'));
      }
    };

    init();
  }, [t]);

  const compareVersion = (latest: string, current: string): boolean => {
    const latestParts = latest.split('.').map(Number);
    const currentParts = current.split('.').map(Number);
    
    for (let i = 0; i < Math.max(latestParts.length, currentParts.length); i++) {
      const l = latestParts[i] || 0;
      const c = currentParts[i] || 0;
      if (l > c) return true;
      if (l < c) return false;
    }
    return false;
  };

  const updateLdapServerHandler = async () => {
    if (!enableLdap) return;
    const token = localStorage.getItem('token') || '';
    try {
      await updateLdapServer(token, ldapServer);
      toast.success(t('LDAP server updated'));
    } catch (error) {
      toast.error(String(error));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = localStorage.getItem('token') || '';

    try {
      await updateWebhookUrl(token, webhookUrl);
      if (adminConfig) {
        await updateAdminConfig(token, adminConfig);
      }
      await updateLdapConfig(token, enableLdap);
      await updateLdapServerHandler();
      
      // Reload backend config
      await getBackendConfig();
      
      toast.success(t('Settings saved successfully!'));
    } catch (error) {
      console.error('Failed to update settings:', error);
      toast.error(t('Failed to update settings'));
    }
  };

  if (!adminConfig) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-muted-foreground">{t('Loading...')}</div>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} className="flex flex-col h-full justify-between space-y-3 text-sm">
      <div className="mt-0.5 space-y-3 overflow-y-scroll scrollbar-hidden h-full">
        <div>
          <div className="mb-3.5">
            <div className="mb-2.5 text-base font-medium">{t('General')}</div>
            <Separator />
          </div>

          {/* Authentication Section */}
          <div className="mb-3">
            <div className="mb-2.5 text-base font-medium">{t('Authentication')}</div>
            <Separator className="my-2" />

            {/* Default User Role */}
            <div className="mb-2.5 flex w-full justify-between items-center">
              <Label className="text-xs font-medium">{t('Default User Role')}</Label>
              <Select
                value={adminConfig.DEFAULT_USER_ROLE}
                onValueChange={(value) => setAdminConfig({ ...adminConfig, DEFAULT_USER_ROLE: value })}
              >
                <SelectTrigger className="w-fit px-2 text-xs h-8">
                  <SelectValue placeholder={t('Select a role')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="pending">{t('pending')}</SelectItem>
                  <SelectItem value="user">{t('user')}</SelectItem>
                  <SelectItem value="admin">{t('admin')}</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Enable New Sign Ups */}
            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('Enable New Sign Ups')}</Label>
              <Switch
                checked={adminConfig.ENABLE_SIGNUP}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_SIGNUP: checked })}
              />
            </div>

            {/* Show Admin Details */}
            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('Show Admin Details in Account Pending Overlay')}</Label>
              <Switch
                checked={adminConfig.SHOW_ADMIN_DETAILS}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, SHOW_ADMIN_DETAILS: checked })}
              />
            </div>

            {/* Pending User Overlay Title */}
            <div className="mb-2.5">
              <Label className="text-xs font-medium mb-2 block">{t('Pending User Overlay Title')}</Label>
              <Textarea
                placeholder={t('Enter a title for the pending user info overlay. Leave empty for default.')}
                value={adminConfig.PENDING_USER_OVERLAY_TITLE}
                onChange={(e) => setAdminConfig({ ...adminConfig, PENDING_USER_OVERLAY_TITLE: e.target.value })}
                className="min-h-[60px]"
              />
            </div>

            {/* Pending User Overlay Content */}
            <div className="mb-2.5">
              <Label className="text-xs font-medium mb-2 block">{t('Pending User Overlay Content')}</Label>
              <Textarea
                placeholder={t('Enter content for the pending user info overlay. Leave empty for default.')}
                value={adminConfig.PENDING_USER_OVERLAY_CONTENT}
                onChange={(e) => setAdminConfig({ ...adminConfig, PENDING_USER_OVERLAY_CONTENT: e.target.value })}
                className="min-h-[60px]"
              />
            </div>

            {/* Enable API Key */}
            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('Enable API Key')}</Label>
              <Switch
                checked={adminConfig.ENABLE_API_KEY}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_API_KEY: checked })}
              />
            </div>

            {adminConfig.ENABLE_API_KEY && (
              <>
                <div className="mb-2.5 flex w-full justify-between items-center pr-2">
                  <Label className="text-xs font-medium">{t('API Key Endpoint Restrictions')}</Label>
                  <Switch
                    checked={adminConfig.ENABLE_API_KEY_ENDPOINT_RESTRICTIONS}
                    onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_API_KEY_ENDPOINT_RESTRICTIONS: checked })}
                  />
                </div>

                {adminConfig.ENABLE_API_KEY_ENDPOINT_RESTRICTIONS && (
                  <div className="flex w-full flex-col pr-2">
                    <Label className="text-xs font-medium">{t('Allowed Endpoints')}</Label>
                    <Input
                      className="w-full mt-1 text-sm"
                      type="text"
                      placeholder="e.g.) /api/v1/messages, /api/v1/channels"
                      value={adminConfig.API_KEY_ALLOWED_ENDPOINTS}
                      onChange={(e) => setAdminConfig({ ...adminConfig, API_KEY_ALLOWED_ENDPOINTS: e.target.value })}
                    />
                    <div className="mt-2 text-xs text-muted-foreground">
                      <a
                        href="https://docs.openwebui.com/getting-started/api-endpoints"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="underline hover:text-foreground"
                      >
                        {t('To learn more about available endpoints, visit our documentation.')}
                      </a>
                    </div>
                  </div>
                )}
              </>
            )}

            {/* JWT Expiration */}
            <div className="mb-2.5 w-full">
              <div className="flex w-full justify-between">
                <Label className="text-xs font-medium">{t('JWT Expiration')}</Label>
              </div>
              <div className="flex mt-2 space-x-2">
                <Input
                  className="w-full text-sm"
                  type="text"
                  placeholder='e.g.) "30m","1h", "10d".'
                  value={adminConfig.JWT_EXPIRES_IN}
                  onChange={(e) => setAdminConfig({ ...adminConfig, JWT_EXPIRES_IN: e.target.value })}
                />
              </div>
              <div className="mt-2 text-xs text-muted-foreground">
                {t('Valid time units:')} <span className="font-medium">{t("'s', 'm', 'h', 'd', 'w' or '-1' for no expiration.")}</span>
              </div>
            </div>

            {/* LDAP Section */}
            <div className="space-y-3">
              <div className="mt-2 space-y-2 pr-1.5">
                <div className="flex justify-between items-center text-sm">
                  <Label className="font-medium">{t('LDAP')}</Label>
                  <Switch
                    checked={enableLdap}
                    onCheckedChange={setEnableLdap}
                  />
                </div>

                {enableLdap && (
                  <div className="flex flex-col gap-1 space-y-2">
                    <div className="flex w-full gap-2">
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Label')}</Label>
                        <Input
                          className="w-full"
                          required
                          placeholder={t('Enter server label')}
                          value={ldapServer.label}
                          onChange={(e) => setLdapServer({ ...ldapServer, label: e.target.value })}
                        />
                      </div>
                      <div className="w-full"></div>
                    </div>

                    <div className="flex w-full gap-2">
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Host')}</Label>
                        <Input
                          className="w-full"
                          required
                          placeholder={t('Enter server host')}
                          value={ldapServer.host}
                          onChange={(e) => setLdapServer({ ...ldapServer, host: e.target.value })}
                        />
                      </div>
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Port')}</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Input
                              className="w-full"
                              type="number"
                              placeholder={t('Enter server port')}
                              value={ldapServer.port}
                              onChange={(e) => setLdapServer({ ...ldapServer, port: e.target.value })}
                            />
                          </TooltipTrigger>
                          <TooltipContent>{t('Default to 389 or 636 if TLS is enabled')}</TooltipContent>
                        </Tooltip>
                      </div>
                    </div>

                    <div className="flex w-full gap-2">
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Application DN')}</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Input
                              className="w-full"
                              required
                              placeholder={t('Enter Application DN')}
                              value={ldapServer.app_dn}
                              onChange={(e) => setLdapServer({ ...ldapServer, app_dn: e.target.value })}
                            />
                          </TooltipTrigger>
                          <TooltipContent>{t('The Application Account DN you bind with for search')}</TooltipContent>
                        </Tooltip>
                      </div>
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Application DN Password')}</Label>
                        <SensitiveInput
                          placeholder={t('Enter Application DN Password')}
                          value={ldapServer.app_dn_password}
                          onChange={(value) => setLdapServer({ ...ldapServer, app_dn_password: value })}
                          type="password"
                        />
                      </div>
                    </div>

                    <div className="flex w-full gap-2">
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Attribute for Mail')}</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Input
                              className="w-full"
                              required
                              placeholder={t('Example: mail')}
                              value={ldapServer.attribute_for_mail}
                              onChange={(e) => setLdapServer({ ...ldapServer, attribute_for_mail: e.target.value })}
                            />
                          </TooltipTrigger>
                          <TooltipContent>{t('The LDAP attribute that maps to the mail that users use to sign in.')}</TooltipContent>
                        </Tooltip>
                      </div>
                    </div>

                    <div className="flex w-full gap-2">
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Attribute for Username')}</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Input
                              className="w-full"
                              required
                              placeholder={t('Example: sAMAccountName or uid or userPrincipalName')}
                              value={ldapServer.attribute_for_username}
                              onChange={(e) => setLdapServer({ ...ldapServer, attribute_for_username: e.target.value })}
                            />
                          </TooltipTrigger>
                          <TooltipContent>{t('The LDAP attribute that maps to the username that users use to sign in.')}</TooltipContent>
                        </Tooltip>
                      </div>
                    </div>

                    <div className="flex w-full gap-2">
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Search Base')}</Label>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Input
                              className="w-full"
                              required
                              placeholder={t('Example: ou=users,dc=foo,dc=example')}
                              value={ldapServer.search_base}
                              onChange={(e) => setLdapServer({ ...ldapServer, search_base: e.target.value })}
                            />
                          </TooltipTrigger>
                          <TooltipContent>{t('The base to search for users')}</TooltipContent>
                        </Tooltip>
                      </div>
                    </div>

                    <div className="flex w-full gap-2">
                      <div className="w-full">
                        <Label className="text-xs font-medium mb-1 block">{t('Search Filters')}</Label>
                        <Input
                          className="w-full"
                          placeholder={t('Example: (&(objectClass=inetOrgPerson)(uid=%s))')}
                          value={ldapServer.search_filters}
                          onChange={(e) => setLdapServer({ ...ldapServer, search_filters: e.target.value })}
                        />
                      </div>
                    </div>

                    <div className="text-xs text-muted-foreground">
                      <a
                        className="underline hover:text-foreground"
                        href="https://ldap.com/ldap-filters/"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {t('Click here for filter guides.')}
                      </a>
                    </div>

                    <div>
                      <div className="flex justify-between items-center text-sm">
                        <Label className="font-medium">{t('TLS')}</Label>
                        <Switch
                          checked={ldapServer.use_tls}
                          onCheckedChange={(checked) => setLdapServer({ ...ldapServer, use_tls: checked })}
                        />
                      </div>

                      {ldapServer.use_tls && (
                        <div className="space-y-2 mt-2">
                          <div className="flex w-full gap-2">
                            <div className="w-full">
                              <Label className="text-xs font-medium mb-1 block">{t('Certificate Path')}</Label>
                              <Input
                                className="w-full"
                                placeholder={t('Enter certificate path')}
                                value={ldapServer.certificate_path}
                                onChange={(e) => setLdapServer({ ...ldapServer, certificate_path: e.target.value })}
                              />
                            </div>
                          </div>

                          <div className="flex justify-between items-center text-xs">
                            <Label className="font-medium">{t('Validate certificate')}</Label>
                            <Switch
                              checked={ldapServer.validate_cert || false}
                              onCheckedChange={(checked) => setLdapServer({ ...ldapServer, validate_cert: checked })}
                            />
                          </div>

                          <div className="flex w-full gap-2">
                            <div className="w-full">
                              <Label className="text-xs font-medium mb-1 block">{t('Ciphers')}</Label>
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <Input
                                    className="w-full"
                                    placeholder={t('Example: ALL')}
                                    value={ldapServer.ciphers}
                                    onChange={(e) => setLdapServer({ ...ldapServer, ciphers: e.target.value })}
                                  />
                                </TooltipTrigger>
                                <TooltipContent>{t('Default to ALL')}</TooltipContent>
                              </Tooltip>
                            </div>
                            <div className="w-full"></div>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Features Section */}
          <div className="mb-3">
            <div className="mb-2.5 text-base font-medium">{t('Features')}</div>
            <Separator className="my-2" />

            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('Enable Community Sharing')}</Label>
              <Switch
                checked={adminConfig.ENABLE_COMMUNITY_SHARING}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_COMMUNITY_SHARING: checked })}
              />
            </div>

            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('Enable Message Rating')}</Label>
              <Switch
                checked={adminConfig.ENABLE_MESSAGE_RATING}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_MESSAGE_RATING: checked })}
              />
            </div>

            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('Notes')} ({t('Beta')})</Label>
              <Switch
                checked={adminConfig.ENABLE_NOTES}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_NOTES: checked })}
              />
            </div>

            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('Channels')} ({t('Beta')})</Label>
              <Switch
                checked={adminConfig.ENABLE_CHANNELS}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_CHANNELS: checked })}
              />
            </div>

            <div className="mb-2.5 flex w-full justify-between items-center pr-2">
              <Label className="text-xs font-medium">{t('User Webhooks')}</Label>
              <Switch
                checked={adminConfig.ENABLE_USER_WEBHOOKS}
                onCheckedChange={(checked) => setAdminConfig({ ...adminConfig, ENABLE_USER_WEBHOOKS: checked })}
              />
            </div>

            <div className="mb-2.5">
              <Label className="text-xs font-medium mb-2 block">{t('Response Watermark')}</Label>
              <Textarea
                placeholder={t('Enter a watermark for the response. Leave empty for none.')}
                value={adminConfig.RESPONSE_WATERMARK}
                onChange={(e) => setAdminConfig({ ...adminConfig, RESPONSE_WATERMARK: e.target.value })}
                className="min-h-[60px]"
              />
            </div>

            <div className="mb-2.5 w-full">
              <div className="flex w-full justify-between">
                <Label className="text-xs font-medium">{t('WebUI URL')}</Label>
              </div>
              <div className="flex mt-2 space-x-2">
                <Input
                  className="w-full text-sm"
                  type="text"
                  placeholder='e.g.) "http://localhost:3000"'
                  value={adminConfig.WEBUI_URL}
                  onChange={(e) => setAdminConfig({ ...adminConfig, WEBUI_URL: e.target.value })}
                />
              </div>
              <div className="mt-2 text-xs text-muted-foreground">
                {t('Enter the public URL of your WebUI. This URL will be used to generate links in the notifications.')}
              </div>
            </div>

            <div className="w-full">
              <div className="flex w-full justify-between">
                <Label className="text-xs font-medium">{t('Webhook URL')}</Label>
              </div>
              <div className="flex mt-2 space-x-2">
                <Input
                  className="w-full text-sm"
                  type="text"
                  placeholder="https://example.com/webhook"
                  value={webhookUrl}
                  onChange={(e) => setWebhookUrl(e.target.value)}
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex justify-end pt-3 text-sm font-medium">
        <Button 
          type="submit"
          className="px-3.5 py-1.5 rounded-full"
        >
          {t('Save')}
        </Button>
      </div>
    </form>
  );
}
